(function () {
  const languages = ["tr","en","de","fr","es","it","pt","ru","ar","zh","ja","ko","hi"];
  const copy = {
    nav: ["Asistan","Assistant","Assistent","Assistant","Asistente","Assistente","Assistente","Ассистент","المساعد","助手","アシスタント","도우미","सहायक"],
    headline: ["Birlikte daha kolay öğren.","Learning is easier together.","Gemeinsam leichter lernen.","Apprendre est plus simple ensemble.","Aprender es más fácil juntos.","Imparare insieme è più facile.","Aprender juntos é mais fácil.","Учиться вместе проще.","التعلّم معًا أسهل.","一起学习，更轻松。","一緒なら、学びはもっと身近に。","함께라서 더 쉬운 학습.","साथ सीखना आसान है।"],
    intro: ["Sorularını sor, görsel paylaş ve derslerini adım adım keşfet.","Ask questions, share images and explore your lessons step by step.","Stelle Fragen, teile Bilder und entdecke deinen Lernstoff Schritt für Schritt.","Posez vos questions, partagez des images et explorez vos cours pas à pas.","Haz preguntas, comparte imágenes y explora tus lecciones paso a paso.","Fai domande, condividi immagini ed esplora le lezioni passo dopo passo.","Faça perguntas, compartilhe imagens e explore suas aulas passo a passo.","Задавайте вопросы, делитесь изображениями и разбирайте уроки шаг за шагом.","اطرح أسئلتك وشارك الصور واستكشف دروسك خطوة بخطوة.","提出问题、分享图片，一步步探索课程内容。","質問や画像を共有して、授業を一歩ずつ理解しましょう。","질문하고 이미지를 공유하며 수업을 차근차근 이해하세요.","सवाल पूछें, चित्र साझा करें और अपने पाठ चरण-दर-चरण समझें।"],
    limited: ["Sınırlı kullanım içerir.","Usage limits apply.","Es gelten Nutzungslimits.","L’utilisation est limitée.","El uso está limitado.","L’utilizzo è limitato.","O uso é limitado.","Действуют лимиты использования.","تخضع الخدمة لحدود استخدام.","使用有额度限制。","利用上限があります。","사용 한도가 적용됩니다.","उपयोग की सीमाएँ लागू हैं।"],
    usage: ["Sohbet ve görsel oluşturma asistan kredisi kullanır. Harcanan kredi, isteğinin uzunluğuna ve türüne göre değişir.","Chat and image creation use assistant credits. The cost depends on the length and type of your request.","Chat und Bilderstellung verbrauchen Assistenten-Credits. Der Verbrauch hängt von Länge und Art deiner Anfrage ab.","Le chat et la création d’images utilisent des crédits. Le coût dépend de la longueur et du type de demande.","El chat y la creación de imágenes usan créditos. El consumo depende de la longitud y el tipo de solicitud.","Chat e creazione di immagini usano crediti. Il consumo dipende dalla lunghezza e dal tipo di richiesta.","Chat e criação de imagens usam créditos. O consumo depende do tamanho e do tipo da solicitação.","Чат и создание изображений расходуют кредиты. Расход зависит от длины и типа запроса.","تستهلك الدردشة وإنشاء الصور رصيد المساعد. يعتمد الاستهلاك على طول الطلب ونوعه.","聊天和图片生成会消耗助手积分，具体取决于请求的长度和类型。","チャットや画像生成にはクレジットを使います。消費量は依頼の長さや種類によって変わります。","채팅과 이미지 생성에는 크레딧이 사용됩니다. 사용량은 요청의 길이와 종류에 따라 달라집니다.","चैट और चित्र बनाने में सहायक क्रेडिट लगते हैं। खर्च अनुरोध की लंबाई और प्रकार पर निर्भर है।"],
    monthly: ["Ücretli abonelik kredileri her ay yenilenir; kullanılmayanlar sonraki aya aktarılmaz.", "Paid subscription credits reset each month. Unused credits do not roll over.", "Credits bezahlter Abos werden monatlich erneuert. Ungenutzte Credits werden nicht übertragen.", "Les crédits des abonnements payants sont renouvelés chaque mois, sans report des crédits inutilisés.", "Los créditos de suscripciones de pago se renuevan cada mes. Los no utilizados no se acumulan.", "I crediti degli abbonamenti a pagamento si rinnovano ogni mese. Quelli inutilizzati non si accumulano.", "Os créditos de assinaturas pagas se renovam todo mês. Os não utilizados não acumulam.", "Кредиты платных подписок обновляются каждый месяц. Неиспользованные кредиты не переносятся.", "يتجدد رصيد الاشتراكات المدفوعة شهريًا، ولا يُرحّل الرصيد غير المستخدم.", "付费订阅积分每月重置，未使用的积分不结转。", "有料プランのクレジットは毎月更新され、未使用分は繰り越されません。", "유료 구독 크레딧은 매달 갱신되며 남은 크레딧은 이월되지 않습니다.", "सशुल्क सदस्यता के क्रेडिट हर महीने नवीनीकृत होते हैं। बचे हुए क्रेडिट अगले महीने नहीं जुड़ते।"],
    topup: ["İhtiyacın olursa ek kredi alabilirsin. Ek krediler 365 gün geçerlidir; ders işleme dakikalarından ayrıdır.","Buy extra credits when you need them. Top-ups last 365 days and are separate from lesson-processing minutes.","Bei Bedarf kannst du Credits nachkaufen. Sie gelten 365 Tage und sind von den Minuten zur Kursverarbeitung getrennt.","Achetez des crédits supplémentaires au besoin. Valables 365 jours, ils sont distincts des minutes de traitement des cours.","Compra créditos extra cuando los necesites. Duran 365 días y son independientes de los minutos para procesar clases.","Acquista crediti extra quando servono. Valgono 365 giorni e sono separati dai minuti di elaborazione delle lezioni.","Compre créditos extras quando precisar. Valem por 365 dias e são separados dos minutos de processamento de aulas.","При необходимости можно купить кредиты. Они действуют 365 дней и не связаны с минутами обработки уроков.","يمكنك شراء رصيد إضافي عند الحاجة. صلاحيته 365 يومًا وهو منفصل عن دقائق معالجة الدروس.","需要时可购买额外积分，有效期为365天，与课程处理分钟数分开计算。","必要に応じて追加購入できます。有効期限は365日で、授業の処理時間とは別に管理されます。","필요할 때 크레딧을 추가 구매하세요. 유효 기간은 365일이며 수업 처리 시간과 별개입니다.","ज़रूरत पर अतिरिक्त क्रेडिट खरीदें। वे 365 दिनों तक मान्य हैं और पाठ संसाधन मिनटों से अलग हैं।"],
    trialnote: ["Üye olmadan günde 3 kısa site rehberi yanıtı alabilirsin. Kişisel sohbet için kaydol ve e-postanı doğrula.","Try 3 short site-guide replies a day without an account. Register and verify your email for personal chat.","Teste täglich 3 kurze Website-Antworten ohne Konto. Für den persönlichen Chat registriere dich und bestätige deine E-Mail.","Essayez 3 réponses courtes par jour sans compte. Inscrivez-vous et vérifiez votre e-mail pour un chat personnel.","Prueba 3 respuestas breves al día sin cuenta. Regístrate y verifica tu correo para el chat personal.","Prova 3 brevi risposte al giorno senza account. Registrati e verifica l’e-mail per la chat personale.","Teste 3 respostas curtas por dia sem conta. Cadastre-se e verifique seu e-mail para o chat pessoal.","Без аккаунта доступны 3 коротких ответа о сайте в день. Для личного чата зарегистрируйтесь и подтвердите почту.","جرّب 3 إجابات قصيرة عن الموقع يوميًا دون حساب. سجّل وأكّد بريدك للدردشة الشخصية.","无需账户，每天可试用3次简短的网站指引。注册并验证邮箱后可使用个人聊天。","アカウントなしで1日3回、短いサイト案内を試せます。個別のチャットには登録とメール確認が必要です。","계정 없이 하루 3회의 짧은 사이트 안내를 체험하세요. 개인 채팅은 가입 후 이메일을 인증하면 이용할 수 있습니다.","बिना खाते रोज़ साइट मार्गदर्शन के 3 छोटे जवाब आज़माएँ। व्यक्तिगत चैट के लिए पंजीकरण और ईमेल सत्यापन करें।"],
    openpage: ["Asistan sayfasını aç","Open assistant page","Assistentenseite öffnen","Ouvrir la page de l’assistant","Abrir página del asistente","Apri la pagina dell’assistente","Abrir página do assistente","Открыть страницу ассистента","افتح صفحة المساعد","打开助手页面","アシスタントページを開く","도우미 페이지 열기","सहायक पृष्ठ खोलें"],
    creditguide: ["Krediler nasıl çalışır?","How do credits work?","Wie funktionieren Credits?","Comment fonctionnent les crédits ?","¿Cómo funcionan los créditos?","Come funzionano i crediti?","Como funcionam os créditos?","Как работают кредиты?","كيف يعمل الرصيد؟","积分如何使用？","クレジットの仕組み","크레딧은 어떻게 사용하나요?","क्रेडिट कैसे काम करते हैं?"],
    balance: ["Kalan kredi: {count}","Credits left: {count}","Verbleibende Credits: {count}","Crédits restants : {count}","Créditos restantes: {count}","Crediti rimasti: {count}","Créditos restantes: {count}","Осталось кредитов: {count}","الرصيد المتبقي: {count}","剩余积分：{count}","残りクレジット：{count}","남은 크레딧: {count}","बचे क्रेडिट: {count}"],
    used: ["Bu yanıt: {count} kredi","This reply: {count} credits","Diese Antwort: {count} Credits","Cette réponse : {count} crédits","Esta respuesta: {count} créditos","Questa risposta: {count} crediti","Esta resposta: {count} créditos","Этот ответ: {count} кредитов","هذه الإجابة: {count} من الرصيد","本次回答：{count}积分","今回の回答：{count}クレジット","이 답변: {count} 크레딧","इस जवाब का खर्च: {count} क्रेडिट"],
    suggeststudy: ["Bir konuyu sade anlat","Explain a topic simply","Erkläre ein Thema einfach","Explique un sujet simplement","Explica un tema de forma sencilla","Spiega un argomento in modo semplice","Explique um tema de forma simples","Объясни тему простыми словами","اشرح موضوعًا ببساطة","简单解释一个主题","テーマをわかりやすく説明して","주제를 쉽게 설명해 줘","किसी विषय को सरलता से समझाएँ"],
    suggestaccount: ["Paketimi nereden görebilirim?","Where can I see my plan?","Wo finde ich meinen Tarif?","Où trouver mon forfait ?","¿Dónde puedo ver mi plan?","Dove trovo il mio piano?","Onde vejo meu plano?","Где посмотреть мой тариф?","أين أجد باقتي؟","在哪里查看我的套餐？","プランはどこで確認できますか？","내 요금제는 어디서 확인하나요?","अपना प्लान कहाँ देखूँ?"],
    suggestinvite: ["Davet programı nasıl çalışır?","How do invitations work?","Wie funktionieren Einladungen?","Comment fonctionnent les invitations ?","¿Cómo funcionan las invitaciones?","Come funzionano gli inviti?","Como funcionam os convites?","Как работают приглашения?","كيف يعمل برنامج الدعوات؟","邀请计划如何运作？","招待プログラムの仕組みは？","초대 프로그램은 어떻게 이용하나요?","आमंत्रण कार्यक्रम कैसे काम करता है?"],
    control: ["Hesabın senin kontrolünde.","Your account stays in your control.","Du behältst die Kontrolle über dein Konto.","Vous gardez le contrôle de votre compte.","Tú mantienes el control de tu cuenta.","Il tuo account resta sotto il tuo controllo.","Sua conta continua sob seu controle.","Ваш аккаунт под вашим контролем.","حسابك تحت سيطرتك.","账户由你掌控。","アカウントの操作はあなたの手で。","계정은 직접 관리하세요.","आपका खाता आपके नियंत्रण में है।"],
    controlnote: ["Asistan yol gösterir. Önerilen sayfayı açmak veya ayarı uygulamak için sen tıklarsın.","The assistant guides you. You choose whether to open a suggested page or apply a setting.","Der Assistent hilft dir. Du entscheidest, ob du eine Seite öffnest oder eine Einstellung anwendest.","L’assistant vous guide. Vous décidez d’ouvrir une page proposée ou d’appliquer un réglage.","El asistente te orienta. Tú decides si abres una página sugerida o aplicas un ajuste.","L’assistente ti guida. Decidi tu se aprire una pagina suggerita o applicare un’impostazione.","O assistente orienta você. Você decide se abre uma página sugerida ou aplica uma configuração.","Ассистент подсказывает. Вы решаете, открывать ли страницу или применять настройку.","يرشدك المساعد، وأنت تقرر فتح الصفحة المقترحة أو تطبيق الإعداد.","助手提供指引，是否打开推荐页面或应用设置，由你点击决定。","アシスタントが案内します。ページを開いたり設定を適用したりするかは、あなたが選びます。","도우미가 안내하면 추천 페이지를 열거나 설정을 적용할지 직접 선택하세요.","सहायक मार्गदर्शन करता है। सुझाया पृष्ठ खोलना या सेटिंग लागू करना आप तय करते हैं।"],
    invitetitle: ["Birlikte çalış, birlikte kazan.","Study together. Earn together.","Zusammen lernen und profitieren.","Étudiez ensemble, gagnez ensemble.","Estudia y gana en compañía.","Studiate insieme, guadagnate insieme.","Estudem juntos. Ganhem juntos.","Учитесь вместе и получайте награды.","ادرسوا معًا واكسبوا معًا.","一起学习，一起获奖励。","一緒に学び、一緒に特典を。","함께 공부하고 혜택도 함께.","साथ पढ़ें, साथ लाभ पाएँ।"],
    invitenote: ["Arkadaşını davet et. Uygun ücretli abonelik alışverişleri ve yenilemelerinde dakika veya indirim kuponu kazanma fırsatı yakala.","Invite a friend. Earn minutes or discount coupons on eligible paid subscription purchases and renewals.","Lade Freunde ein. Erhalte Minuten oder Rabattgutscheine für berechtigte bezahlte Abokäufe und Verlängerungen.","Invitez un ami. Gagnez des minutes ou des coupons sur les achats et renouvellements d’abonnement payants éligibles.","Invita a un amigo. Gana minutos o cupones en compras y renovaciones de suscripciones de pago elegibles.","Invita un amico. Ottieni minuti o coupon per acquisti e rinnovi idonei di abbonamenti a pagamento.","Convide um amigo. Ganhe minutos ou cupons em compras e renovações elegíveis de assinaturas pagas.","Пригласите друга. Получайте минуты или купоны за подходящие покупки и продления платных подписок.","ادعُ صديقًا واكسب دقائق أو قسائم خصم عند شراء الاشتراكات المدفوعة المؤهلة وتجديدها.","邀请好友，可在符合条件的付费订阅购买及续费后获得分钟数或优惠券。","友達を招待すると、対象の有料プランの購入や更新で分数または割引クーポンを獲得できます。","친구를 초대하고 대상 유료 구독 구매와 갱신 시 이용 시간이나 할인 쿠폰을 받으세요.","मित्र को आमंत्रित करें। योग्य सशुल्क सदस्यता खरीद और नवीनीकरण पर मिनट या छूट कूपन पाएँ।"],
    invitelink: ["Davet programını incele","Explore invitations","Einladungen ansehen","Découvrir les invitations","Ver programa de invitaciones","Scopri gli inviti","Conheça os convites","О программе приглашений","استكشف برنامج الدعوات","查看邀请计划","招待プログラムを見る","초대 프로그램 보기","आमंत्रण कार्यक्रम देखें"],
    inviteconditions: ["Kayıt tek başına ödül kazandırmaz. Ödüller koşullara ve kullanım sınırlarına tabidir; ayrıntılar Davetler bölümünde.","Signing up alone earns no reward. Conditions and limits apply; see Invites for details.","Die Registrierung allein bringt keine Prämie. Bedingungen und Limits findest du unter Einladungen.","L’inscription seule ne donne pas de récompense. Conditions et limites dans la rubrique Invitations.","Registrarse no genera recompensas por sí solo. Consulta las condiciones y límites en Invitaciones.","La sola registrazione non dà premi. Condizioni e limiti sono nella sezione Inviti.","Só o cadastro não gera recompensas. Veja condições e limites em Convites.","Регистрация сама по себе не даёт наград. Условия и лимиты — в разделе «Приглашения».","التسجيل وحده لا يمنح مكافأة. تُطبّق شروط وحدود؛ التفاصيل في قسم الدعوات.","仅注册不会获得奖励。奖励受条件及使用上限约束，详情见“邀请”。","登録だけでは特典は付きません。条件と上限は「招待」で確認できます。","가입만으로는 보상이 지급되지 않습니다. 조건과 한도는 초대 메뉴에서 확인하세요.","केवल पंजीकरण से पुरस्कार नहीं मिलता। शर्तों और सीमाओं के लिए आमंत्रण अनुभाग देखें।"],
    firstreward: ["Sen 60 dakika veya %10 kupon seçersin. Arkadaşın 30 dakika kazanabilir.","Choose 60 minutes or a 10% coupon. Your friend can earn 30 minutes.","Wähle 60 Minuten oder 10 % Rabatt. Dein Freund kann 30 Minuten erhalten.","Choisissez 60 minutes ou un coupon de 10 %. Votre ami peut gagner 30 minutes.","Elige 60 minutos o un cupón del 10 %. Tu amigo puede ganar 30 minutos.","Scegli 60 minuti o un coupon del 10%. Il tuo amico può ottenere 30 minuti.","Escolha 60 minutos ou um cupom de 10%. Seu amigo pode ganhar 30 minutos.","Выберите 60 минут или купон на 10 %. Друг может получить 30 минут.","اختر 60 دقيقة أو قسيمة 10٪. ويمكن لصديقك كسب 30 دقيقة.","你可选择60分钟或10%优惠券，好友可获30分钟。","60分または10%割引クーポンを選べます。友達は30分を獲得できます。","60분 또는 10% 쿠폰을 선택하세요. 친구는 30분을 받을 수 있습니다.","60 मिनट या 10% कूपन चुनें। आपके मित्र को 30 मिनट मिल सकते हैं।"],
    renewalreward: ["Sonraki uygun ücretli abonelik alışverişlerinde 30 dakika veya %5 kupon seçebilirsin.","Choose 30 minutes or a 5% coupon on later eligible paid subscription purchases.","Wähle bei weiteren berechtigten bezahlten Abokäufen 30 Minuten oder 5 % Rabatt.","Choisissez 30 minutes ou un coupon de 5 % pour les achats d’abonnement payants éligibles suivants.","Elige 30 minutos o un cupón del 5 % en posteriores compras elegibles de suscripciones de pago.","Scegli 30 minuti o un coupon del 5% sui successivi acquisti idonei di abbonamenti a pagamento.","Escolha 30 minutos ou um cupom de 5% nas próximas compras elegíveis de assinaturas pagas.","За последующие подходящие покупки платных подписок выберите 30 минут или купон на 5 %.","اختر 30 دقيقة أو قسيمة 5٪ عند شراء الاشتراكات المدفوعة المؤهلة لاحقًا.","后续符合条件的付费订阅购买可选择30分钟或5%优惠券。","以降の対象の有料プラン購入では、30分または5%割引クーポンを選べます。","이후 대상 유료 구독 구매 시 30분 또는 5% 쿠폰을 선택할 수 있습니다.","बाद की योग्य सशुल्क सदस्यता खरीद पर 30 मिनट या 5% कूपन चुन सकते हैं।"],
    conditions: ["Koşullar ve kullanım sınırları","Conditions and usage limits","Bedingungen und Nutzungslimits","Conditions et limites d’utilisation","Condiciones y límites de uso","Condizioni e limiti di utilizzo","Condições e limites de uso","Условия и лимиты использования","الشروط وحدود الاستخدام","条件及使用限制","条件と利用上限","조건 및 사용 한도","शर्तें और उपयोग सीमाएँ"],
    welcomeowned: ["Hesabım bölümünde paketini, kullanımını ve davetlerini görebilirsin. Ders dosyaları ve YouTube bağlantıları için çalışma alanını kullan.", "Find your plan, usage and invitations in My account. Use the workspace for lesson files and YouTube links.", "Deinen Tarif, Verbrauch und Einladungen findest du unter Mein Konto. Nutze den Arbeitsbereich für Lerndateien und YouTube-Links.", "Retrouvez votre forfait, votre utilisation et vos invitations dans Mon compte. Utilisez l’espace de travail pour les cours et les liens YouTube.", "Consulta tu plan, uso e invitaciones en Mi cuenta. Usa el espacio de trabajo para archivos de clase y enlaces de YouTube.", "Trovi piano, utilizzo e inviti in Il mio account. Usa lo spazio di lavoro per file didattici e link YouTube.", "Veja seu plano, uso e convites em Minha conta. Use o espaço de trabalho para arquivos de aula e links do YouTube.", "Тариф, расход и приглашения доступны в разделе «Мой аккаунт». Для учебных файлов и ссылок YouTube используйте рабочую область.", "تجد باقتك واستخدامك ودعواتك في حسابي. استخدم مساحة العمل لملفات الدروس وروابط YouTube.", "在“我的账户”中查看套餐、用量和邀请。课程文件和 YouTube 链接请使用工作区。", "マイアカウントでプラン、使用量、招待を確認できます。授業ファイルやYouTubeリンクにはワークスペースをご利用ください。", "내 계정에서 요금제, 사용량, 초대를 확인하세요. 수업 파일과 YouTube 링크는 작업 공간을 이용하세요.", "मेरे खाते में अपना प्लान, उपयोग और आमंत्रण देखें। पाठ फ़ाइलों और YouTube लिंक के लिए कार्य क्षेत्र का उपयोग करें।"],
    mode: ["İşlem", "Mode", "Modus", "Mode", "Modo", "Modalità", "Modo", "Режим", "الوضع", "模式", "モード", "모드", "मोड"],
    chatmode: ["Sohbet", "Chat", "Chat", "Discussion", "Chat", "Chat", "Chat", "Чат", "دردشة", "聊天", "チャット", "채팅", "चैट"],
    imagemode: ["Görsel oluştur", "Create image", "Bild erstellen", "Créer une image", "Crear imagen", "Crea immagine", "Criar imagem", "Создать изображение", "إنشاء صورة", "生成图片", "画像を生成", "이미지 생성", "चित्र बनाएँ"],
    imageprompt: ["İstediğin eğitim görselini tarif et…", "Describe the educational image you want…", "Beschreibe dein gewünschtes Lernbild…", "Décrivez l’illustration pédagogique souhaitée…", "Describe la imagen educativa que quieres…", "Descrivi l’immagine didattica che desideri…", "Descreva a imagem educativa que deseja…", "Опишите нужную учебную иллюстрацию…", "صِف الصورة التعليمية التي تريدها…", "描述你想要的教学图片…", "作りたい学習用画像を説明してください…", "원하는 교육용 이미지를 설명하세요…", "अपना वांछित शैक्षिक चित्र बताएँ…"],
    generated: ["Görselin hazır. Saklamak için indir.", "Your image is ready. Download it to keep it.", "Dein Bild ist fertig. Lade es zum Speichern herunter.", "Votre image est prête. Téléchargez-la pour la conserver.", "Tu imagen está lista. Descárgala para guardarla.", "L’immagine è pronta. Scaricala per conservarla.", "Sua imagem está pronta. Baixe para guardar.", "Изображение готово. Скачайте его, чтобы сохранить.", "صورتك جاهزة. نزّلها للاحتفاظ بها.", "图片已生成，请下载保存。", "画像ができました。保存するにはダウンロードしてください。", "이미지가 준비되었습니다. 다운로드하여 보관하세요.", "चित्र तैयार है। रखने के लिए डाउनलोड करें।"],
    downloadimage: ["Görseli indir", "Download image", "Bild herunterladen", "Télécharger l’image", "Descargar imagen", "Scarica immagine", "Baixar imagem", "Скачать изображение", "تنزيل الصورة", "下载图片", "画像をダウンロード", "이미지 다운로드", "चित्र डाउनलोड करें"],
    shortprompt: ["Görsel açıklamasını biraz kısalt.", "Please shorten the image description.", "Bitte kürze die Bildbeschreibung.", "Raccourcissez la description de l’image.", "Acorta la descripción de la imagen.", "Accorcia la descrizione dell’immagine.", "Encurte a descrição da imagem.", "Сократите описание изображения.", "اختصر وصف الصورة قليلًا.", "请缩短图片描述。", "画像の説明を短くしてください。", "이미지 설명을 줄여 주세요.", "चित्र का विवरण थोड़ा छोटा करें।"],

    uncertain: ["Yanıt durumu henüz doğrulanamadı. Aynı mesajı tekrar göndererek kontrol et.","The response status is not confirmed. Send the same message again to check.","Der Antwortstatus ist noch unbestätigt. Sende dieselbe Nachricht erneut zur Prüfung.","Le statut de la réponse est incertain. Renvoyez le même message pour vérifier.","El estado de la respuesta no está confirmado. Reenvía el mismo mensaje para comprobarlo.","Lo stato della risposta non è confermato. Reinvia lo stesso messaggio per verificare.","O status da resposta não foi confirmado. Envie a mesma mensagem novamente para verificar.","Статус ответа не подтверждён. Отправьте то же сообщение повторно для проверки.","لم تتأكد حالة الإجابة. أرسل الرسالة نفسها مجددًا للتحقق.","回答状态尚未确认。请重新发送相同消息以查看状态。","回答の状態を確認できません。同じメッセージを再送して確認してください。","답변 상태가 확인되지 않았습니다. 같은 메시지를 다시 보내 확인하세요.","उत्तर की स्थिति की पुष्टि नहीं हुई। जाँचने के लिए वही संदेश फिर भेजें।"],
    title: ["LectureSift Asistan","LectureSift Assistant","LectureSift Assistent","Assistant LectureSift","Asistente LectureSift","Assistente LectureSift","Assistente LectureSift","Ассистент LectureSift","مساعد LectureSift","LectureSift 助手","LectureSiftアシスタント","LectureSift 도우미","LectureSift सहायक"],
    ask: ["Site, hesabın veya derslerin hakkında sor…","Ask about the site, your account or your lessons…","Frage zur Website, deinem Konto oder deinen Lektionen…","Posez une question sur le site, votre compte ou vos cours…","Pregunta sobre el sitio, tu cuenta o tus lecciones…","Chiedi del sito, del tuo account o delle lezioni…","Pergunte sobre o site, sua conta ou suas aulas…","Спросите о сайте, аккаунте или уроках…","اسأل عن الموقع أو حسابك أو دروسك…","询问网站、账户或课程…","サイト、アカウント、授業について質問…","사이트, 계정, 수업에 대해 질문하세요…","साइट, खाते या पाठों के बारे में पूछें…"],
    send: ["Gönder","Send","Senden","Envoyer","Enviar","Invia","Enviar","Отправить","إرسال","发送","送信","보내기","भेजें"],
    close: ["Kapat","Close","Schließen","Fermer","Cerrar","Chiudi","Fechar","Закрыть","إغلاق","关闭","閉じる","닫기","बंद करें"],
    clear: ["Yeni sohbet","New chat","Neuer Chat","Nouvelle discussion","Nuevo chat","Nuova chat","Nova conversa","Новый чат","محادثة جديدة","新对话","新しいチャット","새 대화","नई चैट"],
    credits: ["Asistan kredisi","Assistant credits","Assistenten-Credits","Crédits assistant","Créditos del asistente","Crediti assistente","Créditos do assistente","Кредиты ассистента","رصيد المساعد","助手额度","アシスタントクレジット","도우미 크레딧","सहायक क्रेडिट"],
    buy: ["Ek kredi al","Buy more credits","Credits kaufen","Acheter des crédits","Comprar créditos","Acquista crediti","Comprar créditos","Купить кредиты","شراء رصيد إضافي","购买更多额度","クレジットを追加購入","크레딧 추가 구매","और क्रेडिट खरीदें"],
    attach: ["Resim veya video ekle","Attach image or video","Bild oder Video anhängen","Joindre une image ou vidéo","Adjuntar imagen o vídeo","Allega immagine o video","Anexar imagem ou vídeo","Прикрепить изображение или видео","إرفاق صورة أو فيديو","添加图片或视频","画像・動画を添付","이미지 또는 동영상 첨부","चित्र या वीडियो जोड़ें"],
    media: ["Resim: 10 MB. Video: 60 saniye / 50 MB; yalnızca 3 görsel kare incelenir, ses dinlenmez. Tam analiz için Çalışma Alanı.","Image: 10 MB. Video: 60 seconds / 50 MB; only 3 visual frames are analyzed, without audio. Use Workspace for full analysis.","Bild: 10 MB. Video: 60 Sekunden / 50 MB; nur 3 Einzelbilder, ohne Ton. Vollständige Analyse im Arbeitsbereich.","Image : 10 Mo. Vidéo : 60 secondes / 50 Mo ; analyse de 3 images, sans son. Analyse complète dans l’espace de travail.","Imagen: 10 MB. Vídeo: 60 segundos / 50 MB; se analizan 3 fotogramas, sin audio. Análisis completo en el área de trabajo.","Immagine: 10 MB. Video: 60 secondi / 50 MB; analisi di 3 fotogrammi, senza audio. Analisi completa nell’area di lavoro.","Imagem: 10 MB. Vídeo: 60 segundos / 50 MB; análise de 3 quadros, sem áudio. Análise completa na área de trabalho.","Изображение: 10 МБ. Видео: 60 секунд / 50 МБ; анализ 3 кадров без звука. Полный анализ — в рабочей области.","صورة: 10 ميغابايت. فيديو: 60 ثانية / 50 ميغابايت؛ تحليل 3 إطارات بلا صوت. للتحليل الكامل استخدم مساحة العمل.","图片：10 MB。视频：60 秒 / 50 MB；仅分析 3 帧画面，不含音频。完整分析请使用工作区。","画像：10 MB。動画：60秒／50 MB。音声なしの3フレームのみ解析。全体の解析はワークスペースへ。","이미지: 10 MB. 동영상: 60초 / 50 MB. 소리 없이 3개 프레임만 분석합니다. 전체 분석은 작업 공간에서 가능합니다.","चित्र: 10 MB। वीडियो: 60 सेकंड / 50 MB; बिना आवाज़ केवल 3 फ़्रेम का विश्लेषण। पूरे विश्लेषण के लिए कार्य क्षेत्र खोलें।"],
    trial: ["Ücretsiz deneme · günde 3 yanıt", "Free trial · 3 replies a day", "Kostenlos testen · 3 Antworten pro Tag", "Essai gratuit · 3 réponses par jour", "Prueba gratis · 3 respuestas al día", "Prova gratuita · 3 risposte al giorno", "Teste grátis · 3 respostas por dia", "Бесплатно · 3 ответа в день", "تجربة مجانية · 3 إجابات يوميًا", "免费试用 · 每天3次回答", "無料体験 · 1日3回の回答", "무료 체험 · 하루 3회 답변", "मुफ़्त परीक्षण · रोज़ 3 जवाब"],
    welcome: ["Derslerini yükleyerek veya yalnızca YouTube bağlantısı ekleyerek başlayabilirsin. Kişisel sohbet için kaydol; önce siteyle ilgili merak ettiklerini sorabilirsin.", "Start by uploading lessons or adding only YouTube links. Register for personal chat; you can ask about the site first.", "Lade Lernmaterial hoch oder füge ausschließlich YouTube-Links hinzu. Registriere dich für den persönlichen Chat; Fragen zur Website kannst du schon jetzt stellen.", "Commencez par importer vos cours ou ajouter uniquement des liens YouTube. Inscrivez-vous pour un chat personnel ; vous pouvez déjà poser des questions sur le site.", "Empieza subiendo tus clases o añadiendo solo enlaces de YouTube. Regístrate para el chat personal; antes puedes preguntar sobre el sitio.", "Inizia caricando le lezioni o aggiungendo solo link YouTube. Registrati per la chat personale; intanto puoi chiedere informazioni sul sito.", "Comece enviando aulas ou adicionando apenas links do YouTube. Cadastre-se para o chat pessoal; antes, tire suas dúvidas sobre o site.", "Начните с загрузки уроков или добавления ссылок только на YouTube. Для личного чата зарегистрируйтесь; пока можно задать вопросы о сайте.", "ابدأ برفع دروسك أو إضافة روابط YouTube فقط. سجّل للدردشة الشخصية؛ ويمكنك أولًا طرح أسئلة عن الموقع.", "上传课程或添加 YouTube 链接即可开始，链接仅支持 YouTube。注册后可使用个人聊天；现在可以先询问网站相关问题。", "授業をアップロードするか、YouTubeのリンクを追加して始めましょう。リンクはYouTubeのみ対応しています。個別のチャットには登録が必要ですが、サイトについては今すぐ質問できます。", "수업을 업로드하거나 YouTube 링크를 추가해 시작하세요. 링크는 YouTube만 지원합니다. 개인 채팅은 가입 후 이용하고, 지금은 사이트에 대해 질문할 수 있어요.", "पाठ अपलोड करें या केवल YouTube लिंक जोड़कर शुरू करें। व्यक्तिगत चैट के लिए पंजीकरण करें; पहले साइट के बारे में पूछ सकते हैं।"],
    signup: ["Kaydol ve devam et","Register to continue","Registrieren und fortfahren","S’inscrire pour continuer","Regístrate para continuar","Registrati per continuare","Cadastre-se para continuar","Зарегистрироваться","سجّل للمتابعة","注册以继续","登録して続ける","가입하고 계속하기","जारी रखने के लिए पंजीकरण करें"],
    unavailable: ["Kişisel asistan henüz kullanıma açık değil. Site rehberini inceleyebilirsin.","Personal AI chat is not available yet. You can explore the site guide.","Der persönliche KI-Chat ist noch nicht verfügbar. Nutze den Website-Leitfaden.","Le chat IA personnel n’est pas encore disponible. Consultez le guide du site.","El chat personal con IA aún no está disponible. Consulta la guía del sitio.","La chat IA personale non è ancora disponibile. Consulta la guida del sito.","O chat pessoal com IA ainda não está disponível. Consulte o guia do site.","Персональный чат с ИИ пока недоступен. Воспользуйтесь гидом по сайту.","الدردشة الشخصية غير متاحة بعد. يمكنك تصفح دليل الموقع.","个人 AI 聊天尚未开放。您可以查看网站指南。","個人向けAIチャットは準備中です。サイトガイドをご利用ください。","개인 AI 채팅은 아직 제공되지 않습니다. 사이트 안내를 확인하세요.","निजी AI चैट अभी उपलब्ध नहीं है। साइट गाइड देख सकते हैं।"],
    error: ["Yanıt tamamlanamadı; yeniden dene. Tamamlanmayan yanıt için kredi düşülmez.","The response could not be completed; try again. Unanswered requests do not cost credits.","Die Antwort konnte nicht abgeschlossen werden. Versuche es erneut; unbeantwortete Anfragen kosten keine Credits.","La réponse n’a pas abouti. Réessayez ; les demandes sans réponse ne coûtent aucun crédit.","No se completó la respuesta. Inténtalo de nuevo; las solicitudes sin respuesta no consumen créditos.","Risposta non completata. Riprova; le richieste senza risposta non consumano crediti.","A resposta não foi concluída. Tente novamente; solicitações sem resposta não gastam créditos.","Ответ не завершён. Повторите попытку; запросы без ответа не расходуют кредиты.","تعذّر إكمال الإجابة. حاول مجددًا؛ الطلبات بلا إجابة لا تستهلك رصيدًا.","回答未完成，请重试。未获回答的请求不扣额度。","回答を完了できませんでした。再試行してください。未回答のリクエストは課金されません。","답변이 완료되지 않았습니다. 다시 시도하세요. 답변이 없는 요청에는 크레딧이 차감되지 않습니다.","उत्तर पूरा नहीं हुआ; फिर कोशिश करें। बिना उत्तर वाले अनुरोध पर क्रेडिट नहीं कटते।"],
    empty: ["Kredin bu istek için yeterli değil. Daha kısa bir sohbet başlat veya ek kredi al.","You need more credits for this request. Start a shorter chat or buy more credits.","Nicht genug Credits. Starte einen kürzeren Chat oder kaufe weitere Credits.","Crédits insuffisants. Démarrez une discussion plus courte ou achetez des crédits.","Créditos insuficientes. Inicia un chat más corto o compra créditos.","Crediti insufficienti. Avvia una chat più breve o acquista crediti.","Créditos insuficientes. Inicie uma conversa mais curta ou compre créditos.","Недостаточно кредитов. Начните короткий чат или купите кредиты.","الرصيد غير كافٍ. ابدأ محادثة أقصر أو اشترِ رصيدًا إضافيًا.","额度不足。请开始更短的对话或购买更多额度。","クレジットが不足しています。短いチャットを開始するか追加購入してください。","크레딧이 부족합니다. 짧은 대화를 시작하거나 크레딧을 구매하세요.","क्रेडिट कम हैं। छोटी चैट शुरू करें या और क्रेडिट खरीदें।"],
    apply: ["Uygula","Apply","Anwenden","Appliquer","Aplicar","Applica","Aplicar","Применить","تطبيق","应用","適用","적용","लागू करें"],
    waiting: ["Yanıt hazırlanıyor…","Preparing a response…","Antwort wird erstellt…","Préparation de la réponse…","Preparando respuesta…","Preparazione della risposta…","Preparando resposta…","Подготовка ответа…","جارٍ إعداد الإجابة…","正在准备回答…","回答を準備中…","답변 준비 중…","उत्तर तैयार हो रहा है…"],
    rules: ["1 kredi = 1.000 giriş tokenı veya yaklaşık 167 çıkış tokenı. Geçmiş ve görseller sayılır; yanıt başına en az 1 kredi. Paket kredileri aylık yenilenir, birikmez. Ek krediler 365 gün geçerli. Mesaj ve görseller yanıt için OpenAI’a gönderilir; sunucuda sohbet geçmişi tutulmaz.","1 credit = 1,000 input or about 167 output tokens. History and images count; at least 1 credit per answer. Plan credits reset monthly without rollover; top-ups last 365 days. Messages and images are sent to OpenAI to answer; no conversation history is kept on our server.","1 Credit = 1.000 Eingabe- oder ca. 167 Ausgabetokens. Verlauf und Bilder zählen; mindestens 1 Credit pro Antwort. Monatliche Plan-Credits ohne Übertrag; Zusatzcredits 365 Tage. Nachrichten und Bilder gehen an OpenAI; kein Chatverlauf auf unserem Server.","1 crédit = 1 000 tokens d’entrée ou environ 167 de sortie. Historique et images inclus ; minimum 1 crédit par réponse. Crédits mensuels non reportables ; recharges valables 365 jours. Messages et images transmis à OpenAI ; aucun historique conservé sur notre serveur.","1 crédito = 1.000 tokens de entrada o unos 167 de salida. Historial e imágenes cuentan; mínimo 1 crédito por respuesta. Créditos mensuales sin acumular; recargas por 365 días. Mensajes e imágenes se envían a OpenAI; no guardamos historial en el servidor.","1 credito = 1.000 token in ingresso o circa 167 in uscita. Cronologia e immagini contano; minimo 1 credito per risposta. Crediti mensili non cumulabili; ricariche per 365 giorni. Messaggi e immagini inviati a OpenAI; nessuna cronologia sul nostro server.","1 crédito = 1.000 tokens de entrada ou cerca de 167 de saída. Histórico e imagens contam; mínimo 1 crédito por resposta. Créditos mensais não acumulam; recargas duram 365 dias. Mensagens e imagens vão à OpenAI; sem histórico no servidor.","1 кредит = 1000 входных или около 167 выходных токенов. История и изображения учитываются; минимум 1 кредит за ответ. Ежемесячные кредиты без переноса; пополнения на 365 дней. Сообщения и изображения передаются OpenAI; история на нашем сервере не хранится.","رصيد واحد = 1000 رمز إدخال أو نحو 167 رمز إخراج. يُحسب السجل والصور؛ بحد أدنى رصيد واحد للإجابة. رصيد الباقة شهري دون ترحيل، والإضافي صالح 365 يومًا. تُرسل الرسائل والصور إلى OpenAI؛ لا نحتفظ بسجل محادثة على خادمنا.","1 额度 = 1,000 个输入或约 167 个输出 token。历史和图片计入用量，每次回答至少 1 额度。套餐额度每月重置不结转，额外额度有效期 365 天。消息与图片发送至 OpenAI，我们的服务器不保留对话历史。","1クレジット＝入力1,000または出力約167トークン。履歴と画像も対象で回答ごとに最低1クレジット。プラン分は毎月リセット、繰越なし。追加分は365日有効。メッセージと画像はOpenAIへ送信し、当社サーバーに会話履歴は保存しません。","1크레딧 = 입력 1,000 또는 출력 약 167토큰. 기록과 이미지가 포함되며 답변당 최소 1크레딧입니다. 요금제 크레딧은 매월 초기화되며 이월되지 않고 추가 크레딧은 365일 유효합니다. 메시지와 이미지는 OpenAI로 전송되며 서버에 대화 기록을 보관하지 않습니다.","1 क्रेडिट = 1,000 इनपुट या लगभग 167 आउटपुट टोकन। इतिहास और चित्र गिने जाते हैं; प्रति उत्तर कम से कम 1 क्रेडिट। मासिक क्रेडिट आगे नहीं जुड़ते; अतिरिक्त क्रेडिट 365 दिन मान्य हैं। संदेश और चित्र OpenAI को भेजे जाते हैं; हमारे सर्वर पर चैट इतिहास नहीं रहता।"],
  };
  window.LectureSiftAssistantCopy = {
    t(key) { const lang = window.LectureSiftI18n?.language || document.documentElement.lang || "tr"; return copy[key]?.[Math.max(0,languages.indexOf(lang))] || copy[key]?.[1] || key; },
    copy, languages,
  };
  document.querySelectorAll("[data-assistant-copy]").forEach(node => {
    node.textContent = window.LectureSiftAssistantCopy.t(node.dataset.assistantCopy);
  });
})();

// Draft offers remain visibly unavailable until the backend release capability is ready.
window.LectureSiftAssistantOffers = {"INCLUDED":{"free":50,"test":0,"credit":0,"lite":500,"plus":1500,"pro":4000,"max":10000,"business":0},"PACKS":{"ai_1000":1000,"ai_3000":3000,"ai_10000":10000},"PRICES":{"TRY":[14900,34900,99900],"USD":[399,999,2999],"EUR":[399,999,2999],"GBP":[349,849,2499],"CAD":[549,1399,3999],"AUD":[649,1599,4499],"NZD":[699,1799,4999],"JPY":[600,1500,4500],"KRW":[5900,14900,44900],"CNY":[2900,6900,19900],"INR":[34900,89900,249900],"BRL":[2290,5490,15990],"MXN":[7900,19900,59900],"CHF":[399,999,2999],"SEK":[4500,10900,32900],"NOK":[4500,10900,32900],"DKK":[2900,7490,21900],"PLN":[1699,4299,12999],"AED":[1499,3699,10999],"SAR":[1499,3799,11299],"SGD":[549,1399,3999],"HKD":[3199,7999,23999]}};
