(function () {
  const languages = ["tr","en","de","fr","es","it","pt","ru","ar","zh","ja","ko","hi"];
  const copy = {
    title: ["LectureSift Asistan","LectureSift Assistant","LectureSift Assistent","Assistant LectureSift","Asistente LectureSift","Assistente LectureSift","Assistente LectureSift","Ассистент LectureSift","مساعد LectureSift","LectureSift 助手","LectureSiftアシスタント","LectureSift 도우미","LectureSift सहायक"],
    ask: ["Site, hesabın veya derslerin hakkında sor…","Ask about the site, your account or your lessons…","Frage zur Website, deinem Konto oder deinen Lektionen…","Posez une question sur le site, votre compte ou vos cours…","Pregunta sobre el sitio, tu cuenta o tus lecciones…","Chiedi del sito, del tuo account o delle lezioni…","Pergunte sobre o site, sua conta ou suas aulas…","Спросите о сайте, аккаунте или уроках…","اسأل عن الموقع أو حسابك أو دروسك…","询问网站、账户或课程…","サイト、アカウント、授業について質問…","사이트, 계정, 수업에 대해 질문하세요…","साइट, खाते या पाठों के बारे में पूछें…"],
    send: ["Gönder","Send","Senden","Envoyer","Enviar","Invia","Enviar","Отправить","إرسال","发送","送信","보내기","भेजें"],
    close: ["Kapat","Close","Schließen","Fermer","Cerrar","Chiudi","Fechar","Закрыть","إغلاق","关闭","閉じる","닫기","बंद करें"],
    clear: ["Yeni sohbet","New chat","Neuer Chat","Nouvelle discussion","Nuevo chat","Nuova chat","Nova conversa","Новый чат","محادثة جديدة","新对话","新しいチャット","새 대화","नई चैट"],
    credits: ["Asistan kredisi","Assistant credits","Assistenten-Credits","Crédits assistant","Créditos del asistente","Crediti assistente","Créditos do assistente","Кредиты ассистента","رصيد المساعد","助手额度","アシスタントクレジット","도우미 크레딧","सहायक क्रेडिट"],
    buy: ["Ek kredi al","Buy more credits","Credits kaufen","Acheter des crédits","Comprar créditos","Acquista crediti","Comprar créditos","Купить кредиты","شراء رصيد إضافي","购买更多额度","クレジットを追加購入","크레딧 추가 구매","और क्रेडिट खरीदें"],
    attach: ["Resim veya video ekle","Attach image or video","Bild oder Video anhängen","Joindre une image ou vidéo","Adjuntar imagen o vídeo","Allega immagine o video","Anexar imagem ou vídeo","Прикрепить изображение или видео","إرفاق صورة أو فيديو","添加图片或视频","画像・動画を添付","이미지 또는 동영상 첨부","चित्र या वीडियो जोड़ें"],
    media: ["Resim: 10 MB. Video: 60 saniye / 50 MB; yalnızca 3 görsel kare incelenir, ses dinlenmez. Tam analiz için Çalışma Alanı.","Image: 10 MB. Video: 60 seconds / 50 MB; only 3 visual frames are analyzed, without audio. Use Workspace for full analysis.","Bild: 10 MB. Video: 60 Sekunden / 50 MB; nur 3 Einzelbilder, ohne Ton. Vollständige Analyse im Arbeitsbereich.","Image : 10 Mo. Vidéo : 60 secondes / 50 Mo ; analyse de 3 images, sans son. Analyse complète dans l’espace de travail.","Imagen: 10 MB. Vídeo: 60 segundos / 50 MB; se analizan 3 fotogramas, sin audio. Análisis completo en el área de trabajo.","Immagine: 10 MB. Video: 60 secondi / 50 MB; analisi di 3 fotogrammi, senza audio. Analisi completa nell’area di lavoro.","Imagem: 10 MB. Vídeo: 60 segundos / 50 MB; análise de 3 quadros, sem áudio. Análise completa na área de trabalho.","Изображение: 10 МБ. Видео: 60 секунд / 50 МБ; анализ 3 кадров без звука. Полный анализ — в рабочей области.","صورة: 10 ميغابايت. فيديو: 60 ثانية / 50 ميغابايت؛ تحليل 3 إطارات بلا صوت. للتحليل الكامل استخدم مساحة العمل.","图片：10 MB。视频：60 秒 / 50 MB；仅分析 3 帧画面，不含音频。完整分析请使用工作区。","画像：10 MB。動画：60秒／50 MB。音声なしの3フレームのみ解析。全体の解析はワークスペースへ。","이미지: 10 MB. 동영상: 60초 / 50 MB. 소리 없이 3개 프레임만 분석합니다. 전체 분석은 작업 공간에서 가능합니다.","चित्र: 10 MB। वीडियो: 60 सेकंड / 50 MB; बिना आवाज़ केवल 3 फ़्रेम का विश्लेषण। पूरे विश्लेषण के लिए कार्य क्षेत्र खोलें।"],
    trial: ["Kısa site rehberi · örnek yanıt","Quick site guide · sample response","Kurzer Website-Leitfaden · Beispielantwort","Guide rapide du site · réponse exemple","Guía rápida del sitio · respuesta de ejemplo","Guida rapida al sito · risposta di esempio","Guia rápido do site · resposta de exemplo","Краткий гид по сайту · пример ответа","دليل سريع للموقع · إجابة نموذجية","网站简明指南 · 示例回答","サイトガイド・回答例","간단한 사이트 안내 · 예시 답변","संक्षिप्त साइट गाइड · उदाहरण उत्तर"],
    welcome: ["Ders dosyalarını Çalışma Alanı’na yükleyebilir, özet, quiz ve bilgi kartları hazırlayabilirsin. Bağlantı alanı yalnızca YouTube videolarını kabul eder. Paketleri Planlar’da, kendi kullanımını Hesabım’da görebilirsin. Kişisel yapay zekâ sohbeti için kaydol ve e-postanı doğrula.","Upload lessons in Workspace to create summaries, quizzes and flashcards. The URL field accepts only YouTube videos. Find packages in Plans and your usage in My account. Register and verify your email for personal AI chat.","Lade Lektionen im Arbeitsbereich hoch, um Zusammenfassungen, Quiz und Lernkarten zu erstellen. Das URL-Feld akzeptiert nur YouTube-Videos. Pakete findest du unter Tarife, deinen Verbrauch unter Mein Konto. Registriere dich und bestätige deine E-Mail für den persönlichen KI-Chat.","Importez vos cours dans l’espace de travail pour créer résumés, quiz et fiches. Le champ URL accepte uniquement YouTube. Les forfaits sont dans Forfaits et votre utilisation dans Mon compte. Inscrivez-vous et vérifiez votre e-mail pour le chat IA personnel.","Sube lecciones al área de trabajo para crear resúmenes, cuestionarios y tarjetas. El campo URL solo acepta YouTube. Consulta paquetes en Planes y tu uso en Mi cuenta. Regístrate y verifica tu correo para el chat personal con IA.","Carica lezioni nell’area di lavoro per creare riassunti, quiz e schede. Il campo URL accetta solo YouTube. Trovi i pacchetti in Piani e l’utilizzo in Il mio account. Registrati e verifica l’email per la chat IA personale.","Envie aulas na área de trabalho para criar resumos, questionários e cartões. O campo URL aceita apenas YouTube. Veja pacotes em Planos e seu uso em Minha conta. Cadastre-se e confirme seu e-mail para conversar com a IA.","Загрузите уроки в рабочую область для создания конспектов, тестов и карточек. Поле ссылки принимает только YouTube. Пакеты находятся в разделе Тарифы, расход — в Мой аккаунт. Зарегистрируйтесь и подтвердите почту для персонального чата с ИИ.","ارفع دروسك في مساحة العمل لإنشاء ملخصات واختبارات وبطاقات. حقل الرابط يقبل فيديوهات YouTube فقط. تجد الباقات في الخطط واستخدامك في حسابي. سجّل وأكّد بريدك للدردشة الشخصية مع الذكاء الاصطناعي.","在工作区上传课程，即可生成摘要、测验和抽认卡。链接栏仅支持 YouTube 视频。套餐在“套餐”页面，用量在“我的账户”查看。注册并验证邮箱后即可使用个人 AI 聊天。","ワークスペースに授業をアップロードすると要約、クイズ、暗記カードを作れます。URL欄はYouTube動画のみ対応しています。料金はプラン、利用量はマイアカウントで確認できます。個人向けAIチャットは登録とメール認証後に利用できます。","작업 공간에 수업을 업로드하여 요약, 퀴즈, 학습 카드를 만드세요. URL 입력란은 YouTube 동영상만 지원합니다. 요금제에서 상품을, 내 계정에서 사용량을 확인하세요. 개인 AI 채팅을 이용하려면 가입하고 이메일을 인증하세요.","सारांश, क्विज़ और फ़्लैशकार्ड बनाने के लिए कार्य क्षेत्र में पाठ अपलोड करें। URL फ़ील्ड केवल YouTube वीडियो स्वीकार करता है। प्लान में पैकेज और मेरे खाते में उपयोग देखें। निजी AI चैट के लिए पंजीकरण और ईमेल सत्यापन करें।"],
    signup: ["Kaydol ve devam et","Register to continue","Registrieren und fortfahren","S’inscrire pour continuer","Regístrate para continuar","Registrati per continuare","Cadastre-se para continuar","Зарегистрироваться","سجّل للمتابعة","注册以继续","登録して続ける","가입하고 계속하기","जारी रखने के लिए पंजीकरण करें"],
    unavailable: ["Kişisel asistan henüz kullanıma açık değil. Site rehberini inceleyebilirsin.","Personal AI chat is not available yet. You can explore the site guide.","Der persönliche KI-Chat ist noch nicht verfügbar. Nutze den Website-Leitfaden.","Le chat IA personnel n’est pas encore disponible. Consultez le guide du site.","El chat personal con IA aún no está disponible. Consulta la guía del sitio.","La chat IA personale non è ancora disponibile. Consulta la guida del sito.","O chat pessoal com IA ainda não está disponível. Consulte o guia do site.","Персональный чат с ИИ пока недоступен. Воспользуйтесь гидом по сайту.","الدردشة الشخصية غير متاحة بعد. يمكنك تصفح دليل الموقع.","个人 AI 聊天尚未开放。您可以查看网站指南。","個人向けAIチャットは準備中です。サイトガイドをご利用ください。","개인 AI 채팅은 아직 제공되지 않습니다. 사이트 안내를 확인하세요.","निजी AI चैट अभी उपलब्ध नहीं है। साइट गाइड देख सकते हैं।"],
    error: ["Yanıt tamamlanamadı; yeniden dene. Tamamlanmayan yanıt için kredi düşülmez.","The response could not be completed; try again. Unanswered requests do not cost credits.","Die Antwort konnte nicht abgeschlossen werden. Versuche es erneut; unbeantwortete Anfragen kosten keine Credits.","La réponse n’a pas abouti. Réessayez ; les demandes sans réponse ne coûtent aucun crédit.","No se completó la respuesta. Inténtalo de nuevo; las solicitudes sin respuesta no consumen créditos.","Risposta non completata. Riprova; le richieste senza risposta non consumano crediti.","A resposta não foi concluída. Tente novamente; solicitações sem resposta não gastam créditos.","Ответ не завершён. Повторите попытку; запросы без ответа не расходуют кредиты.","تعذّر إكمال الإجابة. حاول مجددًا؛ الطلبات بلا إجابة لا تستهلك رصيدًا.","回答未完成，请重试。未获回答的请求不扣额度。","回答を完了できませんでした。再試行してください。未回答のリクエストは課金されません。","답변이 완료되지 않았습니다. 다시 시도하세요. 답변이 없는 요청에는 크레딧이 차감되지 않습니다.","उत्तर पूरा नहीं हुआ; फिर कोशिश करें। बिना उत्तर वाले अनुरोध पर क्रेडिट नहीं कटते।"],
    empty: ["Kredin bu istek için yeterli değil. Daha kısa bir sohbet başlat veya ek kredi al.","You need more credits for this request. Start a shorter chat or buy more credits.","Nicht genug Credits. Starte einen kürzeren Chat oder kaufe weitere Credits.","Crédits insuffisants. Démarrez une discussion plus courte ou achetez des crédits.","Créditos insuficientes. Inicia un chat más corto o compra créditos.","Crediti insufficienti. Avvia una chat più breve o acquista crediti.","Créditos insuficientes. Inicie uma conversa mais curta ou compre créditos.","Недостаточно кредитов. Начните короткий чат или купите кредиты.","الرصيد غير كافٍ. ابدأ محادثة أقصر أو اشترِ رصيدًا إضافيًا.","额度不足。请开始更短的对话或购买更多额度。","クレジットが不足しています。短いチャットを開始するか追加購入してください。","크레딧이 부족합니다. 짧은 대화를 시작하거나 크레딧을 구매하세요.","क्रेडिट कम हैं। छोटी चैट शुरू करें या और क्रेडिट खरीदें।"],
    apply: ["Uygula","Apply","Anwenden","Appliquer","Aplicar","Applica","Aplicar","Применить","تطبيق","应用","適用","적용","लागू करें"],
    waiting: ["Yanıt hazırlanıyor…","Preparing a response…","Antwort wird erstellt…","Préparation de la réponse…","Preparando respuesta…","Preparazione della risposta…","Preparando resposta…","Подготовка ответа…","جارٍ إعداد الإجابة…","正在准备回答…","回答を準備中…","답변 준비 중…","उत्तर तैयार हो रहा है…"],
    rules: ["1 kredi = 1.000 giriş tokenı veya yaklaşık 167 çıkış tokenı. Geçmiş ve görseller sayılır; yanıt başına en az 1 kredi. Paket kredileri aylık yenilenir, birikmez. Ek krediler 365 gün geçerli. Mesaj ve görseller yanıt için OpenAI’a gönderilir; sunucuda sohbet geçmişi tutulmaz.","1 credit = 1,000 input or about 167 output tokens. History and images count; at least 1 credit per answer. Plan credits reset monthly without rollover; top-ups last 365 days. Messages and images are sent to OpenAI to answer; no conversation history is kept on our server.","1 Credit = 1.000 Eingabe- oder ca. 167 Ausgabetokens. Verlauf und Bilder zählen; mindestens 1 Credit pro Antwort. Monatliche Plan-Credits ohne Übertrag; Zusatzcredits 365 Tage. Nachrichten und Bilder gehen an OpenAI; kein Chatverlauf auf unserem Server.","1 crédit = 1 000 tokens d’entrée ou environ 167 de sortie. Historique et images inclus ; minimum 1 crédit par réponse. Crédits mensuels non reportables ; recharges valables 365 jours. Messages et images transmis à OpenAI ; aucun historique conservé sur notre serveur.","1 crédito = 1.000 tokens de entrada o unos 167 de salida. Historial e imágenes cuentan; mínimo 1 crédito por respuesta. Créditos mensuales sin acumular; recargas por 365 días. Mensajes e imágenes se envían a OpenAI; no guardamos historial en el servidor.","1 credito = 1.000 token in ingresso o circa 167 in uscita. Cronologia e immagini contano; minimo 1 credito per risposta. Crediti mensili non cumulabili; ricariche per 365 giorni. Messaggi e immagini inviati a OpenAI; nessuna cronologia sul nostro server.","1 crédito = 1.000 tokens de entrada ou cerca de 167 de saída. Histórico e imagens contam; mínimo 1 crédito por resposta. Créditos mensais não acumulam; recargas duram 365 dias. Mensagens e imagens vão à OpenAI; sem histórico no servidor.","1 кредит = 1000 входных или около 167 выходных токенов. История и изображения учитываются; минимум 1 кредит за ответ. Ежемесячные кредиты без переноса; пополнения на 365 дней. Сообщения и изображения передаются OpenAI; история на нашем сервере не хранится.","رصيد واحد = 1000 رمز إدخال أو نحو 167 رمز إخراج. يُحسب السجل والصور؛ بحد أدنى رصيد واحد للإجابة. رصيد الباقة شهري دون ترحيل، والإضافي صالح 365 يومًا. تُرسل الرسائل والصور إلى OpenAI؛ لا نحتفظ بسجل محادثة على خادمنا.","1 额度 = 1,000 个输入或约 167 个输出 token。历史和图片计入用量，每次回答至少 1 额度。套餐额度每月重置不结转，额外额度有效期 365 天。消息与图片发送至 OpenAI，我们的服务器不保留对话历史。","1クレジット＝入力1,000または出力約167トークン。履歴と画像も対象で回答ごとに最低1クレジット。プラン分は毎月リセット、繰越なし。追加分は365日有効。メッセージと画像はOpenAIへ送信し、当社サーバーに会話履歴は保存しません。","1크레딧 = 입력 1,000 또는 출력 약 167토큰. 기록과 이미지가 포함되며 답변당 최소 1크레딧입니다. 요금제 크레딧은 매월 초기화되며 이월되지 않고 추가 크레딧은 365일 유효합니다. 메시지와 이미지는 OpenAI로 전송되며 서버에 대화 기록을 보관하지 않습니다.","1 क्रेडिट = 1,000 इनपुट या लगभग 167 आउटपुट टोकन। इतिहास और चित्र गिने जाते हैं; प्रति उत्तर कम से कम 1 क्रेडिट। मासिक क्रेडिट आगे नहीं जुड़ते; अतिरिक्त क्रेडिट 365 दिन मान्य हैं। संदेश और चित्र OpenAI को भेजे जाते हैं; हमारे सर्वर पर चैट इतिहास नहीं रहता।"],
  };
  window.LectureSiftAssistantCopy = {
    t(key) { const lang = window.LectureSiftI18n?.language || document.documentElement.lang || "tr"; return copy[key]?.[Math.max(0,languages.indexOf(lang))] || copy[key]?.[1] || key; },
    copy, languages,
  };
})();

// Draft offers remain visibly unavailable until the backend release capability is ready.
window.LectureSiftAssistantOffers = {"INCLUDED":{"free":50,"test":0,"credit":0,"lite":500,"plus":1500,"pro":4000,"max":10000,"business":0},"PACKS":{"ai_1000":1000,"ai_3000":3000,"ai_10000":10000},"PRICES":{"TRY":[14900,34900,99900],"USD":[399,999,2999],"EUR":[399,999,2999],"GBP":[349,849,2499],"CAD":[549,1399,3999],"AUD":[649,1599,4499],"NZD":[699,1799,4999],"JPY":[600,1500,4500],"KRW":[5900,14900,44900],"CNY":[2900,6900,19900],"INR":[34900,89900,249900],"BRL":[2290,5490,15990],"MXN":[7900,19900,59900],"CHF":[399,999,2999],"SEK":[4500,10900,32900],"NOK":[4500,10900,32900],"DKK":[2900,7490,21900],"PLN":[1699,4299,12999],"AED":[1499,3699,10999],"SAR":[1499,3799,11299],"SGD":[549,1399,3999],"HKD":[3199,7999,23999]}};
