(function () {
  const codes = ["tr","en","de","fr","es","it","pt","ru","ar","zh","ja","ko","hi"];
  const languages = {tr:"Türkçe",en:"English",de:"Deutsch",fr:"Français",es:"Español",it:"Italiano",pt:"Português",ru:"Русский",ar:"العربية",zh:"中文",ja:"日本語",ko:"한국어",hi:"हिन्दी"};
  const locales = {tr:"tr-TR",en:"en-US",de:"de-DE",fr:"fr-FR",es:"es-ES",it:"it-IT",pt:"pt-BR",ru:"ru-RU",ar:"ar-SA",zh:"zh-CN",ja:"ja-JP",ko:"ko-KR",hi:"hi-IN"};
  const rows = {
    "language.label":["Site dili","Site language","Seitensprache","Langue du site","Idioma del sitio","Lingua del sito","Idioma do site","Язык сайта","لغة الموقع","网站语言","サイト言語","사이트 언어","साइट की भाषा"],
    "nav.workspace":["Çalışma alanına dön","Back to workspace","Zurück zum Arbeitsbereich","Retour à l’espace de travail","Volver al espacio de trabajo","Torna all’area di lavoro","Voltar ao espaço de trabalho","Вернуться в рабочую область","العودة إلى مساحة العمل","返回工作区","ワークスペースに戻る","작업 공간으로 돌아가기","वर्कस्पेस पर वापस जाएँ"],
    "nav.features":["Özellikler","Features","Funktionen","Fonctionnalités","Funciones","Funzionalità","Recursos","Возможности","الميزات","功能","機能","기능","विशेषताएँ"],
    "nav.plans":["Planlar","Plans","Tarife","Forfaits","Planes","Piani","Planos","Тарифы","الخطط","套餐","プラン","요금제","प्लान"],
    "nav.about":["Hakkımızda","About","Über uns","À propos","Nosotros","Chi siamo","Sobre","О нас","من نحن","关于我们","私たちについて","소개","हमारे बारे में"],
    "nav.login":["Giriş","Sign in","Anmelden","Connexion","Iniciar sesión","Accedi","Entrar","Войти","تسجيل الدخول","登录","ログイン","로그인","साइन इन"],
    "auth.logout":["Çıkış yap","Sign out","Abmelden","Se déconnecter","Cerrar sesión","Esci","Sair","Выйти","تسجيل الخروج","退出登录","ログアウト","로그아웃","साइन आउट"],
    "field.firstName":["Ad","First name","Vorname","Prénom","Nombre","Nome","Nome","Имя","الاسم الأول","名字","名","이름","पहला नाम"],
    "field.lastName":["Soyad","Last name","Nachname","Nom","Apellido","Cognome","Sobrenome","Фамилия","اسم العائلة","姓氏","姓","성","उपनाम"],
    "field.phone":["Telefon","Phone","Telefon","Téléphone","Teléfono","Telefono","Telefone","Телефон","الهاتف","电话","電話","전화","फ़ोन"],
    "field.phoneOptional":["Telefon (isteğe bağlı)","Phone (optional)","Telefon (optional)","Téléphone (facultatif)","Teléfono (opcional)","Telefono (opzionale)","Telefone (opcional)","Телефон (необязательно)","الهاتف (اختياري)","电话（可选）","電話（任意）","전화(선택)","फ़ोन (वैकल्पिक)"],
    "field.country":["Ülke","Country","Land","Pays","País","Paese","País","Страна","البلد","国家/地区","国","국가","देश"],
    "field.interfaceLanguage":["Arayüz dili","Interface language","Oberflächensprache","Langue de l’interface","Idioma de la interfaz","Lingua dell’interfaccia","Idioma da interface","Язык интерфейса","لغة الواجهة","界面语言","表示言語","인터페이스 언어","इंटरफ़ेस भाषा"],
    "field.currentPassword":["Mevcut parola","Current password","Aktuelles Passwort","Mot de passe actuel","Contraseña actual","Password attuale","Senha atual","Текущий пароль","كلمة المرور الحالية","当前密码","現在のパスワード","현재 비밀번호","वर्तमान पासवर्ड"],
    "field.newPassword":["Yeni parola","New password","Neues Passwort","Nouveau mot de passe","Nueva contraseña","Nuova password","Nova senha","Новый пароль","كلمة المرور الجديدة","新密码","新しいパスワード","새 비밀번호","नया पासवर्ड"],
    "field.confirmPassword":["Yeni parolayı tekrar et","Confirm new password","Neues Passwort bestätigen","Confirmer le nouveau mot de passe","Confirmar nueva contraseña","Conferma nuova password","Confirmar nova senha","Повторите новый пароль","تأكيد كلمة المرور الجديدة","确认新密码","新しいパスワードを確認","새 비밀번호 확인","नए पासवर्ड की पुष्टि करें"],
    "auth.email":["E-posta","Email","E-Mail","E-mail","Correo electrónico","E-mail","E-mail","Эл. почта","البريد الإلكتروني","电子邮箱","メール","이메일","ईमेल"],
    "auth.password":["Parola","Password","Passwort","Mot de passe","Contraseña","Password","Senha","Пароль","كلمة المرور","密码","パスワード","비밀번호","पासवर्ड"],
    "auth.passwordRepeat":["Parolayı tekrar et","Repeat password","Passwort wiederholen","Répéter le mot de passe","Repetir contraseña","Ripeti password","Repetir senha","Повторите пароль","تكرار كلمة المرور","再次输入密码","パスワードを再入力","비밀번호 확인","पासवर्ड दोहराएँ"],
    "auth.signIn":["Giriş yap","Sign in","Anmelden","Se connecter","Iniciar sesión","Accedi","Entrar","Войти","تسجيل الدخول","登录","ログイン","로그인","साइन इन"],
    "auth.create":["Hesap oluştur","Create account","Konto erstellen","Créer un compte","Crear cuenta","Crea account","Criar conta","Создать аккаунт","إنشاء حساب","创建账户","アカウント作成","계정 만들기","खाता बनाएँ"],
    "auth.home":["← Ana sayfa","← Home","← Startseite","← Accueil","← Inicio","← Home","← Início","← Главная","← الرئيسية","← 首页","← ホーム","← 홈","← होम"],
    "auth.accountLabel":["LectureSift hesabı","LectureSift account","LectureSift-Konto","Compte LectureSift","Cuenta LectureSift","Account LectureSift","Conta LectureSift","Аккаунт LectureSift","حساب LectureSift","LectureSift 账户","LectureSift アカウント","LectureSift 계정","LectureSift खाता"],
    "auth.loginHelp":["Çalışma alanını açmak için e-posta ve parolanı gir.","Enter your email and password to open your workspace.","Gib E-Mail und Passwort ein, um deinen Arbeitsbereich zu öffnen.","Saisissez votre e-mail et votre mot de passe.","Introduce tu correo y contraseña para abrir tu espacio.","Inserisci e-mail e password per aprire l’area di lavoro.","Digite e-mail e senha para abrir seu espaço.","Введите почту и пароль, чтобы открыть рабочую область.","أدخل البريد وكلمة المرور لفتح مساحة العمل.","输入邮箱和密码以打开工作区。","メールとパスワードを入力してください。","이메일과 비밀번호를 입력하세요.","वर्कस्पेस खोलने के लिए ईमेल और पासवर्ड डालें।"],
    "auth.forgot":["Parolamı unuttum","Forgot password","Passwort vergessen","Mot de passe oublié","Olvidé mi contraseña","Password dimenticata","Esqueci a senha","Забыли пароль","نسيت كلمة المرور","忘记密码","パスワードを忘れた","비밀번호 찾기","पासवर्ड भूल गए"],
    "auth.resend":["Doğrulama e-postasını yenile","Resend verification email","Bestätigungs-E-Mail erneut senden","Renvoyer l’e-mail de vérification","Reenviar correo de verificación","Invia di nuovo l’e-mail","Reenviar e-mail de verificação","Отправить письмо повторно","إعادة إرسال رسالة التحقق","重新发送验证邮件","確認メールを再送","인증 메일 재전송","सत्यापन ईमेल फिर भेजें"],
    "auth.noAccount":["Henüz hesabın yok mu?","Don’t have an account yet?","Noch kein Konto?","Pas encore de compte ?","¿Aún no tienes cuenta?","Non hai un account?","Ainda não tem conta?","Ещё нет аккаунта?","ليس لديك حساب؟","还没有账户？","アカウントをお持ちでないですか？","계정이 없으신가요?","अभी खाता नहीं है?"],
    "auth.freeCreate":["Ücretsiz hesap oluştur","Create a free account","Kostenloses Konto erstellen","Créer un compte gratuit","Crear cuenta gratis","Crea account gratuito","Criar conta grátis","Создать бесплатный аккаунт","إنشاء حساب مجاني","免费创建账户","無料アカウント作成","무료 계정 만들기","मुफ़्त खाता बनाएँ"],
    "auth.registerEyebrow":["Ücretsiz hesabını oluştur","Create your free account","Kostenloses Konto erstellen","Créez votre compte gratuit","Crea tu cuenta gratis","Crea il tuo account gratuito","Crie sua conta grátis","Создайте бесплатный аккаунт","أنشئ حسابك المجاني","创建免费账户","無料アカウントを作成","무료 계정 만들기","अपना मुफ़्त खाता बनाएँ"],
    "auth.registerTitle":["Ders çalışmanın dağınık parçalarını tek yerde birleştir.","Bring every scattered part of studying into one place.","Bringe alle verstreuten Lernteile an einen Ort.","Réunissez toutes les étapes de vos études en un seul endroit.","Reúne todas las partes del estudio en un solo lugar.","Riunisci ogni parte dello studio in un unico posto.","Reúna todas as partes dos estudos em um só lugar.","Соберите все части обучения в одном месте.","اجمع كل أجزاء الدراسة في مكان واحد.","将分散的学习环节汇集到一处。","学習のすべてを一か所にまとめます。","흩어진 학습 과정을 한곳에 모으세요.","पढ़ाई के सभी बिखरे हिस्सों को एक जगह लाएँ।"],
    "auth.registerText":["Video ve ses kayıtlarından özet, transkript, quiz, bilgi kartı, slayt ve indirilebilir çalışma dosyaları üret.","Create summaries, transcripts, quizzes, flashcards, slides, and downloadable study files from video and audio.","Erstelle Zusammenfassungen, Transkripte, Quiz, Lernkarten und Dateien aus Video und Audio.","Créez résumés, transcriptions, quiz, cartes et fichiers à partir de vidéos et d’audios.","Crea resúmenes, transcripciones, cuestionarios, tarjetas y archivos desde vídeo y audio.","Crea riepiloghi, trascrizioni, quiz, flashcard e file da video e audio.","Crie resumos, transcrições, quizzes, cartões e arquivos a partir de vídeo e áudio.","Создавайте конспекты, транскрипты, тесты, карточки и файлы из видео и аудио.","أنشئ ملخصات ونصوصًا واختبارات وبطاقات وملفات من الفيديو والصوت.","从视频和音频生成摘要、转录、测验、闪卡和文件。","動画・音声から要約、文字起こし、クイズ、カード、ファイルを作成。","영상과 음성에서 요약, 전사, 퀴즈, 카드, 파일을 만드세요.","वीडियो और ऑडियो से सारांश, ट्रांसक्रिप्ट, क्विज़, कार्ड और फ़ाइलें बनाएँ।"],
    "auth.secureVerification":["E-posta ile güvenli doğrulama","Secure email verification","Sichere E-Mail-Bestätigung","Vérification sécurisée par e-mail","Verificación segura por correo","Verifica e-mail sicura","Verificação segura por e-mail","Безопасное подтверждение почты","تحقق آمن بالبريد","安全邮箱验证","安全なメール認証","안전한 이메일 인증","सुरक्षित ईमेल सत्यापन"],
    "auth.verifyChoice":["E-postandaki bağlantıyı kullan veya altı haneli kodu doğrulama ekranına gir.","Use the email link or enter the six-digit code on the verification screen.","Nutze den E-Mail-Link oder gib den sechsstelligen Code ein.","Utilisez le lien ou saisissez le code à six chiffres.","Usa el enlace o introduce el código de seis dígitos.","Usa il link o inserisci il codice a sei cifre.","Use o link ou digite o código de seis dígitos.","Откройте ссылку или введите шестизначный код.","استخدم الرابط أو أدخل الرمز المكون من ستة أرقام.","使用邮件链接或输入六位验证码。","メールのリンクまたは6桁コードを使用します。","이메일 링크 또는 6자리 코드를 사용하세요.","ईमेल लिंक उपयोग करें या छह अंकों का कोड डालें।"],
    "auth.languages13":["13 dilde çalışma alanı","Workspace in 13 languages","Arbeitsbereich in 13 Sprachen","Espace de travail en 13 langues","Espacio en 13 idiomas","Area di lavoro in 13 lingue","Espaço em 13 idiomas","Рабочая область на 13 языках","مساحة عمل بـ13 لغة","支持13种语言","13言語対応","13개 언어 지원","13 भाषाओं में वर्कस्पेस"],
    "auth.freeMinutes":["60 ücretsiz dakika","60 free minutes","60 kostenlose Minuten","60 minutes gratuites","60 minutos gratis","60 minuti gratuiti","60 minutos grátis","60 бесплатных минут","60 دقيقة مجانية","60分钟免费额度","60分無料","무료 60분","60 मुफ़्त मिनट"],
    "auth.verifyEmailTitle":["E-posta adresini doğrula","Verify your email","E-Mail bestätigen","Vérifiez votre e-mail","Verifica tu correo","Verifica la tua e-mail","Verifique seu e-mail","Подтвердите почту","تحقق من بريدك","验证邮箱","メールを確認","이메일 인증","ईमेल सत्यापित करें"],
    "auth.sixDigitCode":["Altı haneli kod","Six-digit code","Sechsstelliger Code","Code à six chiffres","Código de seis dígitos","Codice a sei cifre","Código de seis dígitos","Шестизначный код","رمز من ستة أرقام","六位验证码","6桁コード","6자리 코드","छह अंकों का कोड"],
    "auth.verifyByCode":["Kodla doğrula","Verify with code","Mit Code bestätigen","Vérifier avec le code","Verificar con código","Verifica con codice","Verificar com código","Подтвердить кодом","التحقق بالرمز","使用验证码验证","コードで確認","코드로 인증","कोड से सत्यापित करें"],
    "auth.acceptRequired":["Devam etmek için kullanım ve gizlilik koşullarını kabul et.","Accept the terms and privacy notice to continue.","Akzeptiere die Bedingungen und Datenschutzhinweise, um fortzufahren.","Acceptez les conditions et la politique de confidentialité pour continuer.","Acepta las condiciones y la privacidad para continuar.","Accetta termini e informativa privacy per continuare.","Aceite os termos e a privacidade para continuar.","Примите условия и политику конфиденциальности.","وافق على الشروط وإشعار الخصوصية للمتابعة.","请接受条款和隐私声明以继续。","続行するには規約とプライバシー通知に同意してください。","계속하려면 약관과 개인정보 처리방침에 동의하세요.","जारी रखने के लिए शर्तें और गोपनीयता सूचना स्वीकार करें।"],
    "auth.preparing":["Hesap hazırlanıyor…","Creating account…","Konto wird erstellt…","Création du compte…","Creando cuenta…","Creazione account…","Criando conta…","Создание аккаунта…","جارٍ إنشاء الحساب…","正在创建账户…","アカウントを作成中…","계정 생성 중…","खाता बनाया जा रहा है…"],
    "auth.signingIn":["Giriş yapılıyor…","Signing in…","Anmeldung…","Connexion…","Iniciando sesión…","Accesso…","Entrando…","Вход…","جارٍ تسجيل الدخول…","正在登录…","ログイン中…","로그인 중…","साइन इन हो रहा है…"],
    "auth.enterEmailFirst":["Önce e-posta adresini gir.","Enter your email address first.","Gib zuerst deine E-Mail-Adresse ein.","Saisissez d’abord votre e-mail.","Introduce primero tu correo.","Inserisci prima l’e-mail.","Digite primeiro seu e-mail.","Сначала введите адрес почты.","أدخل بريدك الإلكتروني أولاً.","请先输入邮箱地址。","先にメールアドレスを入力してください。","먼저 이메일 주소를 입력하세요.","पहले ईमेल पता डालें।"],
    "auth.emailVerified":["E-posta doğrulandı","Email verified","E-Mail bestätigt","E-mail vérifié","Correo verificado","E-mail verificata","E-mail verificado","Почта подтверждена","تم تأكيد البريد","邮箱已验证","メール確認済み","이메일 인증 완료","ईमेल सत्यापित"],
    "auth.accountActive":["Hesabın etkin. LectureSift çalışma alanına geçebilirsin.","Your account is active. You can open the LectureSift workspace.","Dein Konto ist aktiv. Du kannst den LectureSift-Arbeitsbereich öffnen.","Votre compte est actif. Vous pouvez ouvrir l’espace LectureSift.","Tu cuenta está activa. Ya puedes abrir LectureSift.","Il tuo account è attivo. Puoi aprire LectureSift.","Sua conta está ativa. Você pode abrir o LectureSift.","Аккаунт активен. Можно открыть LectureSift.","حسابك نشط ويمكنك فتح مساحة LectureSift.","账户已激活，可以进入 LectureSift 工作区。","アカウントが有効になりました。LectureSiftを開けます。","계정이 활성화되었습니다. LectureSift를 열 수 있습니다.","आपका खाता सक्रिय है। अब LectureSift खोल सकते हैं।"],
    "auth.checkingLink":["Güvenli bağlantın kontrol ediliyor.","Checking your secure link.","Sicherer Link wird geprüft.","Vérification du lien sécurisé.","Comprobando el enlace seguro.","Controllo del link sicuro.","Verificando o link seguro.","Проверяем безопасную ссылку.","جارٍ التحقق من الرابط الآمن.","正在检查安全链接。","安全なリンクを確認中です。","보안 링크를 확인 중입니다.","सुरक्षित लिंक जाँचा जा रहा है।"],
    "auth.linkFailed":["Bağlantı doğrulanamadı","Link could not be verified","Link konnte nicht bestätigt werden","Le lien n’a pas pu être vérifié","No se pudo verificar el enlace","Impossibile verificare il link","Não foi possível verificar o link","Не удалось подтвердить ссылку","تعذر التحقق من الرابط","无法验证链接","リンクを確認できませんでした","링크를 인증할 수 없습니다","लिंक सत्यापित नहीं हो सका"],
    "auth.tryCode":["E-postandaki altı haneli kodu kullanmayı deneyebilirsin.","Try the six-digit code in your email.","Versuche den sechsstelligen Code aus der E-Mail.","Essayez le code à six chiffres reçu par e-mail.","Prueba el código de seis dígitos del correo.","Prova il codice a sei cifre ricevuto via e-mail.","Tente o código de seis dígitos do e-mail.","Попробуйте шестизначный код из письма.","جرّب الرمز المكون من ستة أرقام في بريدك.","请尝试邮件中的六位验证码。","メールの6桁コードをお試しください。","이메일의 6자리 코드를 사용해 보세요.","ईमेल में मिला छह अंकों का कोड आज़माएँ।"],
    "auth.verifying":["Doğrulanıyor…","Verifying…","Bestätigung…","Vérification…","Verificando…","Verifica…","Verificando…","Проверка…","جارٍ التحقق…","正在验证…","確認中…","인증 중…","सत्यापन हो रहा है…"],
    "auth.sending":["Gönderiliyor…","Sending…","Wird gesendet…","Envoi…","Enviando…","Invio…","Enviando…","Отправка…","جارٍ الإرسال…","正在发送…","送信中…","전송 중…","भेजा जा रहा है…"],
    "auth.sendReset":["Yenileme bağlantısı gönder","Send reset link","Link zum Zurücksetzen senden","Envoyer le lien","Enviar enlace","Invia link di ripristino","Enviar link de redefinição","Отправить ссылку","إرسال رابط إعادة التعيين","发送重置链接","リセットリンクを送信","재설정 링크 보내기","रीसेट लिंक भेजें"],
    "auth.resetMissing":["Şifre yenileme bağlantısı eksik.","Password reset link is missing.","Link zum Zurücksetzen fehlt.","Le lien de réinitialisation manque.","Falta el enlace de restablecimiento.","Manca il link di ripristino.","O link de redefinição está ausente.","Ссылка для сброса отсутствует.","رابط إعادة تعيين كلمة المرور مفقود.","缺少密码重置链接。","パスワード再設定リンクがありません。","비밀번호 재설정 링크가 없습니다.","पासवर्ड रीसेट लिंक मौजूद नहीं है।"],
    "auth.resetting":["Şifre yenileniyor…","Resetting password…","Passwort wird geändert…","Réinitialisation…","Restableciendo contraseña…","Reimpostazione password…","Redefinindo senha…","Сброс пароля…","جارٍ إعادة تعيين كلمة المرور…","正在重置密码…","パスワードを再設定中…","비밀번호 재설정 중…","पासवर्ड रीसेट हो रहा है…"],
    "auth.resetPassword":["Şifreyi yenile","Reset password","Passwort zurücksetzen","Réinitialiser le mot de passe","Restablecer contraseña","Reimposta password","Redefinir senha","Сбросить пароль","إعادة تعيين كلمة المرور","重置密码","パスワードを再設定","비밀번호 재설정","पासवर्ड रीसेट करें"],
    "account.eyebrow":["Hesabım","My account","Mein Konto","Mon compte","Mi cuenta","Il mio account","Minha conta","Мой аккаунт","حسابي","我的账户","マイアカウント","내 계정","मेरा खाता"],
    "account.verified":["✓ E-posta doğrulandı","✓ Email verified","✓ E-Mail bestätigt","✓ E-mail vérifié","✓ Correo verificado","✓ E-mail verificata","✓ E-mail verificado","✓ Почта подтверждена","✓ تم تأكيد البريد","✓ 邮箱已验证","✓ メール確認済み","✓ 이메일 인증됨","✓ ईमेल सत्यापित"],
    "account.usageTitle":["Kullanım ve krediler","Usage and credits","Nutzung und Guthaben","Utilisation et crédits","Uso y créditos","Utilizzo e crediti","Uso e créditos","Использование и кредиты","الاستخدام والرصيد","使用量与额度","利用状況とクレジット","사용량 및 크레딧","उपयोग और क्रेडिट"],
    "account.remaining":["Toplam kalan dakika","Total minutes remaining","Verbleibende Minuten gesamt","Minutes restantes","Minutos restantes","Minuti rimanenti","Minutos restantes","Осталось минут","إجمالي الدقائق المتبقية","剩余总分钟数","残り合計分数","총 남은 시간","कुल शेष मिनट"],
    "account.creditBalance":["Ek kredi bakiyesi","Extra credit balance","Zusätzliches Guthaben","Solde de crédits supplémentaires","Saldo de crédito extra","Credito aggiuntivo","Saldo de crédito extra","Дополнительные минуты","رصيد إضافي","额外额度","追加クレジット","추가 크레딧","अतिरिक्त क्रेडिट"],
    "account.buyMinutes":["Ek dakika satın al","Buy extra minutes","Zusätzliche Minuten kaufen","Acheter des minutes","Comprar minutos extra","Acquista minuti extra","Comprar minutos extras","Купить минуты","شراء دقائق إضافية","购买额外分钟","追加分数を購入","추가 시간 구매","अतिरिक्त मिनट खरीदें"],
    "account.comparePlans":["Planları karşılaştır","Compare plans","Tarife vergleichen","Comparer les forfaits","Comparar planes","Confronta i piani","Comparar planos","Сравнить тарифы","مقارنة الخطط","比较套餐","プランを比較","요금제 비교","प्लान की तुलना करें"],
    "account.planTitle":["Plan ve hesap","Plan and account","Tarif und Konto","Forfait et compte","Plan y cuenta","Piano e account","Plano e conta","Тариф и аккаунт","الخطة والحساب","套餐与账户","プランとアカウント","요금제 및 계정","प्लान और खाता"],
    "account.currentPlan":["Mevcut plan","Current plan","Aktueller Tarif","Forfait actuel","Plan actual","Piano attuale","Plano atual","Текущий тариф","الخطة الحالية","当前套餐","現在のプラン","현재 요금제","वर्तमान प्लान"],
    "account.unlimited":["Sınırsız","Unlimited","Unbegrenzt","Illimité","Ilimitado","Illimitato","Ilimitado","Без ограничений","غير محدود","无限","無制限","무제한","असीमित"],
    "account.usedMinutes":["{count} dk kullanıldı","{count} min used","{count} Min. genutzt","{count} min utilisées","{count} min usados","{count} min utilizzati","{count} min usados","Использовано {count} мин","تم استخدام {count} دقيقة","已使用 {count} 分钟","{count}分使用","{count}분 사용","{count} मिनट उपयोग"],
    "profile.title":["Profil bilgileri","Profile details","Profildaten","Informations du profil","Datos del perfil","Dati del profilo","Dados do perfil","Данные профиля","بيانات الملف الشخصي","个人资料","プロフィール情報","프로필 정보","प्रोफ़ाइल विवरण"],
    "profile.save":["Profili kaydet","Save profile","Profil speichern","Enregistrer le profil","Guardar perfil","Salva profilo","Salvar perfil","Сохранить профиль","حفظ الملف الشخصي","保存资料","プロフィールを保存","프로필 저장","प्रोफ़ाइल सहेजें"],
    "profile.notAdded":["Eklenmedi","Not added","Nicht hinzugefügt","Non ajouté","No añadido","Non aggiunto","Não adicionado","Не указан","غير مضاف","未添加","未登録","추가되지 않음","नहीं जोड़ा गया"],
    "preferences.title":["Ülke ve dil tercihleri","Country and language preferences","Land und Sprache","Préférences de pays et de langue","Preferencias de país e idioma","Preferenze paese e lingua","Preferências de país e idioma","Страна и язык","تفضيلات البلد واللغة","国家与语言偏好","国と言語の設定","국가 및 언어 설정","देश और भाषा प्राथमिकताएँ"],
    "preferences.save":["Tercihleri kaydet","Save preferences","Einstellungen speichern","Enregistrer les préférences","Guardar preferencias","Salva preferenze","Salvar preferências","Сохранить настройки","حفظ التفضيلات","保存偏好","設定を保存","설정 저장","प्राथमिकताएँ सहेजें"],
    "security.passwordTitle":["Parola değiştir","Change password","Passwort ändern","Changer le mot de passe","Cambiar contraseña","Cambia password","Alterar senha","Сменить пароль","تغيير كلمة المرور","更改密码","パスワード変更","비밀번호 변경","पासवर्ड बदलें"],
    "security.changePassword":["Parolayı değiştir","Change password","Passwort ändern","Changer le mot de passe","Cambiar contraseña","Cambia password","Alterar senha","Сменить пароль","تغيير كلمة المرور","更改密码","パスワードを変更","비밀번호 변경","पासवर्ड बदलें"],
    "security.supportTitle":["Güvenlik ve destek","Security and support","Sicherheit und Support","Sécurité et assistance","Seguridad y soporte","Sicurezza e supporto","Segurança e suporte","Безопасность и поддержка","الأمان والدعم","安全与支持","セキュリティとサポート","보안 및 지원","सुरक्षा और सहायता"],
    "security.help":["Parolanı düzenli olarak yenile; giriş bağlantılarını ve doğrulama kodlarını kimseyle paylaşma.","Update your password regularly and never share sign-in links or verification codes.","Aktualisiere dein Passwort regelmäßig und teile keine Anmelde- oder Bestätigungscodes.","Renouvelez régulièrement votre mot de passe et ne partagez jamais vos liens ou codes.","Actualiza tu contraseña y no compartas enlaces ni códigos de verificación.","Aggiorna regolarmente la password e non condividere link o codici.","Atualize sua senha e não compartilhe links nem códigos de verificação.","Регулярно меняйте пароль и никому не сообщайте ссылки и коды.","حدّث كلمة المرور بانتظام ولا تشارك الروابط أو رموز التحقق.","请定期更新密码，不要分享登录链接或验证码。","パスワードを定期的に更新し、リンクや確認コードを共有しないでください。","비밀번호를 정기적으로 변경하고 링크나 인증 코드를 공유하지 마세요.","पासवर्ड नियमित बदलें और लिंक या सत्यापन कोड साझा न करें।"],
    "security.resetLink":["Parolayı e-postayla yenile","Reset password by email","Passwort per E-Mail zurücksetzen","Réinitialiser par e-mail","Restablecer por correo","Reimposta via e-mail","Redefinir por e-mail","Сбросить по почте","إعادة التعيين بالبريد","通过邮件重置","メールで再設定","이메일로 재설정","ईमेल से रीसेट करें"],
    "security.contact":["Destek iste","Contact support","Support kontaktieren","Contacter l’assistance","Contactar soporte","Contatta assistenza","Contatar suporte","Связаться с поддержкой","طلب الدعم","联系支持","サポートに連絡","지원 문의","सहायता से संपर्क करें"],
    "payment.ordersTitle":["Ödeme siparişleri","Payment orders","Zahlungsaufträge","Commandes de paiement","Órdenes de pago","Ordini di pagamento","Pedidos de pagamento","Платежные заказы","طلبات الدفع","付款订单","支払い注文","결제 주문","भुगतान ऑर्डर"],
    "payment.orderNumber":["Sipariş no","Order number","Bestellnummer","Numéro de commande","Número de pedido","Numero ordine","Número do pedido","Номер заказа","رقم الطلب","订单号","注文番号","주문 번호","ऑर्डर नंबर"],
    "payment.iban":["IBAN","IBAN","IBAN","IBAN","IBAN","IBAN","IBAN","IBAN","رقم IBAN","IBAN","IBAN","IBAN","IBAN"],
    "payment.accountHolder":["Hesap sahibi","Account holder","Kontoinhaber","Titulaire du compte","Titular de la cuenta","Intestatario","Titular da conta","Владелец счёта","صاحب الحساب","账户名","口座名義","예금주","खाता धारक"],
    "payment.bankName":["Banka","Bank","Bank","Banque","Banco","Banca","Banco","Банк","البنك","银行","銀行","은행","बैंक"],
    "payment.noOrders":["Henüz ödeme siparişin yok.","You have no payment orders yet.","Du hast noch keine Zahlungsaufträge.","Vous n’avez pas encore de commande.","Aún no tienes órdenes de pago.","Non hai ancora ordini di pagamento.","Você ainda não tem pedidos.","У вас пока нет заказов.","لا توجد طلبات دفع بعد.","暂无付款订单。","支払い注文はまだありません。","아직 결제 주문이 없습니다.","अभी कोई भुगतान ऑर्डर नहीं है।"],
    "payment.methodsTitle":["Ödeme seçenekleri","Payment options","Zahlungsoptionen","Options de paiement","Opciones de pago","Opzioni di pagamento","Opções de pagamento","Способы оплаты","خيارات الدفع","付款方式","お支払い方法","결제 옵션","भुगतान विकल्प"],
    "payment.methodsText":["Havale şu anda kullanılabilir. Kart ve yerel ödeme seçenekleri PayTR etkinleştirildiğinde burada açılacak.","Bank transfer is available now. Cards and local methods will appear here when PayTR is enabled.","Banküberweisung ist verfügbar. Karten und lokale Methoden folgen mit PayTR.","Le virement est disponible. Les cartes et moyens locaux seront ajoutés avec PayTR.","La transferencia está disponible. Las tarjetas y métodos locales se añadirán con PayTR.","Il bonifico è disponibile. Carte e metodi locali arriveranno con PayTR.","Transferência disponível. Cartões e métodos locais chegarão com PayTR.","Банковский перевод доступен. Карты появятся после подключения PayTR.","التحويل البنكي متاح، وستظهر البطاقات والطرق المحلية بعد تفعيل PayTR.","目前支持银行转账，启用 PayTR 后将提供银行卡和本地方式。","銀行振込が利用可能です。PayTR 有効化後にカード等を追加します。","현재 계좌이체 가능하며 PayTR 활성화 후 카드 결제가 추가됩니다.","बैंक ट्रांसफ़र उपलब्ध है; PayTR सक्रिय होने पर कार्ड विकल्प जुड़ेंगे।"],
    "payment.bankTransfer":["Banka havalesi","Bank transfer","Banküberweisung","Virement bancaire","Transferencia bancaria","Bonifico bancario","Transferência bancária","Банковский перевод","تحويل بنكي","银行转账","銀行振込","계좌이체","बैंक ट्रांसफ़र"],
    "payment.loading":["Bilgiler yükleniyor…","Loading details…","Daten werden geladen…","Chargement…","Cargando…","Caricamento…","Carregando…","Загрузка…","جارٍ التحميل…","正在加载…","読み込み中…","불러오는 중…","लोड हो रहा है…"],
    "payment.available":["Havale ile ödeme kullanılabilir.","Bank transfer is available.","Banküberweisung ist verfügbar.","Le virement est disponible.","La transferencia está disponible.","Il bonifico è disponibile.","A transferência está disponível.","Банковский перевод доступен.","التحويل البنكي متاح.","可以银行转账。","銀行振込を利用できます。","계좌이체를 사용할 수 있습니다.","बैंक ट्रांसफ़र उपलब्ध है।"],
    "payment.notConfigured":["Havale bilgileri henüz etkin değil.","Bank details are not enabled yet.","Bankdaten sind noch nicht aktiviert.","Les coordonnées bancaires ne sont pas actives.","Los datos bancarios aún no están activos.","I dati bancari non sono ancora attivi.","Os dados bancários ainda não estão ativos.","Банковские реквизиты ещё не активны.","بيانات التحويل غير مفعلة بعد.","银行信息尚未启用。","振込先はまだ有効ではありません。","계좌 정보가 아직 활성화되지 않았습니다.","बैंक विवरण अभी सक्रिय नहीं हैं।"],
    "payment.unavailable":["Ödeme bilgileri şu anda alınamıyor.","Payment details are currently unavailable.","Zahlungsdaten sind derzeit nicht verfügbar.","Les informations de paiement sont indisponibles.","Los datos de pago no están disponibles.","I dati di pagamento non sono disponibili.","Os dados de pagamento estão indisponíveis.","Платёжные данные недоступны.","بيانات الدفع غير متاحة حاليًا.","暂时无法获取付款信息。","支払い情報を取得できません。","결제 정보를 불러올 수 없습니다.","भुगतान विवरण उपलब्ध नहीं है।"],
    "payment.card":["Kart ve yerel yöntemler","Cards and local methods","Karten und lokale Methoden","Cartes et moyens locaux","Tarjetas y métodos locales","Carte e metodi locali","Cartões e métodos locais","Карты и местные способы","البطاقات والطرق المحلية","银行卡与本地方式","カード・現地決済","카드 및 현지 결제","कार्ड और स्थानीय तरीके"],
    "payment.cardPending":["PayTR mağaza onayı ve anahtarları tamamlandığında güvenli ödeme açılacak.","Secure checkout will open after PayTR approval and credentials are complete.","Sicheres Bezahlen startet nach PayTR-Freigabe und Zugangsdaten.","Le paiement sécurisé sera activé après validation de PayTR.","El pago seguro se abrirá tras la aprobación de PayTR.","Il pagamento sicuro sarà attivo dopo l’approvazione PayTR.","O checkout seguro abrirá após a aprovação do PayTR.","Безопасная оплата откроется после одобрения PayTR.","سيتم فتح الدفع الآمن بعد موافقة PayTR وإضافة المفاتيح.","PayTR 审核并配置密钥后将开放安全支付。","PayTR 承認とキー設定後に安全な決済を開始します。","PayTR 승인 및 키 설정 후 안전 결제가 열립니다.","PayTR अनुमोदन और कुंजियाँ मिलने पर सुरक्षित भुगतान खुलेगा।"],
    "plans.extraTitle":["Planına ek dakika gerektiğinde","When you need extra minutes","Wenn du mehr Minuten brauchst","Quand vous avez besoin de minutes","Cuando necesites más minutos","Quando servono minuti extra","Quando precisar de minutos","Когда нужны дополнительные минуты","عندما تحتاج دقائق إضافية","需要额外分钟时","追加分数が必要なとき","추가 시간이 필요할 때","जब अतिरिक्त मिनट चाहिए"],
    "plans.extraText":["Dakika Paketi aboneliğini değiştirmez; mevcut planının üzerine tek seferlik ek kredi ekler. Satın alma ve kalan kredi Hesabım sayfasında görünür.","The Minute Pack does not change your subscription; it adds one-time credit to your current plan.","Das Minutenpaket ändert dein Abo nicht, sondern ergänzt einmaliges Guthaben.","Le pack de minutes ajoute un crédit ponctuel sans modifier l’abonnement.","El paquete añade crédito único sin cambiar tu suscripción.","Il pacchetto aggiunge credito una tantum senza cambiare l’abbonamento.","O pacote adiciona crédito único sem alterar a assinatura.","Пакет минут добавляет разовый кредит, не меняя подписку.","تضيف حزمة الدقائق رصيدًا لمرة واحدة دون تغيير الاشتراك.","分钟包会增加一次性额度，不会改变订阅。","分数パックは契約を変更せず、追加クレジットを付与します。","시간 팩은 구독을 바꾸지 않고 일회성 크레딧을 추가합니다.","मिनट पैक सदस्यता बदले बिना एकमुश्त क्रेडिट जोड़ता है।"],
    "plans.manageCredits":["Kredilerimi yönet","Manage credits","Guthaben verwalten","Gérer les crédits","Gestionar créditos","Gestisci crediti","Gerenciar créditos","Управлять кредитами","إدارة الرصيد","管理额度","クレジット管理","크레딧 관리","क्रेडिट प्रबंधित करें"],
    "plans.compareTitle":["Hakları karşılaştır","Compare entitlements","Leistungen vergleichen","Comparer les droits","Comparar derechos","Confronta i diritti","Comparar benefícios","Сравнить возможности","مقارنة المزايا","比较权益","権限を比較","혜택 비교","अधिकारों की तुलना"],
    "plans.compareText":["Tüm planları; dakika, üretim hakları, dosyalar, öncelik ve ekip kapasitesiyle ayrıntılı karşılaştır.","Compare every plan by minutes, learning outputs, files, priority, and team capacity.","Vergleiche Minuten, Lerninhalte, Dateien, Priorität und Teamgröße.","Comparez minutes, contenus, fichiers, priorité et capacité d’équipe.","Compara minutos, materiales, archivos, prioridad y capacidad de equipo.","Confronta minuti, contenuti, file, priorità e capacità del team.","Compare minutos, materiais, arquivos, prioridade e equipe.","Сравните минуты, материалы, файлы, приоритет и места в команде.","قارن الدقائق والمخرجات والملفات والأولوية وسعة الفريق.","按分钟数、学习产出、文件、优先级和团队规模比较。","分数、教材、ファイル、優先度、チーム人数を比較できます。","시간, 학습 자료, 파일, 우선순위, 팀 인원을 비교하세요.","मिनट, सामग्री, फ़ाइल, प्राथमिकता और टीम क्षमता की तुलना करें।"],
    "plans.right":["Hak","Entitlement","Leistung","Droit","Derecho","Diritto","Benefício","Возможность","الميزة","权益","項目","혜택","अधिकार"],
    "plans.billingType":["Ödeme türü","Billing type","Abrechnung","Type de paiement","Tipo de pago","Tipo di pagamento","Tipo de cobrança","Тип оплаты","نوع الدفع","付费类型","支払い種別","결제 유형","भुगतान प्रकार"],
    "plans.subscription":["Aylık abonelik","Monthly subscription","Monatsabo","Abonnement mensuel","Suscripción mensual","Abbonamento mensile","Assinatura mensal","Месячная подписка","اشتراك شهري","月度订阅","月額契約","월간 구독","मासिक सदस्यता"],
    "plans.oneTime":["Tek ödeme","One-time payment","Einmalzahlung","Paiement unique","Pago único","Pagamento unico","Pagamento único","Разовый платёж","دفعة واحدة","一次性付款","一回払い","일회성 결제","एकमुश्त भुगतान"],
    "plans.quote":["Teklif","Quote","Angebot","Devis","Cotización","Preventivo","Orçamento","По запросу","عرض سعر","报价","見積もり","견적","कोटेशन"],
    "plans.minutes":["İşleme dakikası","Processing minutes","Verarbeitungsminuten","Minutes de traitement","Minutos de procesamiento","Minuti di elaborazione","Minutos de processamento","Минуты обработки","دقائق المعالجة","处理分钟数","処理分数","처리 시간","प्रोसेसिंग मिनट"],
    "plans.quiz":["Quiz sorusu / işlem","Quiz questions / job","Quizfragen / Auftrag","Questions / traitement","Preguntas / proceso","Domande / elaborazione","Perguntas / tarefa","Вопросов / обработку","أسئلة / عملية","测验题/任务","クイズ/処理","퀴즈/작업","क्विज़/कार्य"],
    "plans.cards":["Bilgi kartı / işlem","Flashcards / job","Lernkarten / Auftrag","Cartes / traitement","Tarjetas / proceso","Flashcard / elaborazione","Flashcards / tarefa","Карточек / обработку","بطاقات / عملية","闪卡/任务","カード/処理","플래시카드/작업","फ़्लैशकार्ड/कार्य"],
    "plans.summaries":["Özet profilleri","Summary profiles","Zusammenfassungen","Profils de résumé","Perfiles de resumen","Profili di riepilogo","Perfis de resumo","Профили конспекта","أنماط الملخص","摘要模式","要約プロファイル","요약 프로필","सारांश प्रोफ़ाइल"],
    "plans.exports":["Dosya biçimleri","File formats","Dateiformate","Formats de fichier","Formatos de archivo","Formati file","Formatos de arquivo","Форматы файлов","صيغ الملفات","文件格式","ファイル形式","파일 형식","फ़ाइल प्रारूप"],
    "plans.priority":["İşlem önceliği","Processing priority","Priorität","Priorité","Prioridad","Priorità","Prioridade","Приоритет","أولوية المعالجة","处理优先级","処理優先度","처리 우선순위","प्रोसेसिंग प्राथमिकता"],
    "plans.teamSeats":["Ekip kullanıcıları","Team seats","Teamplätze","Places d’équipe","Usuarios de equipo","Posti team","Usuários da equipe","Места в команде","مقاعد الفريق","团队席位","チーム席数","팀 좌석","टीम सीट"],
    "plans.multiSource":["Çoklu video ve ayrı ses/slayt","Multiple video and separate audio/slides","Mehrere Videos und getrennte Quellen","Vidéos multiples et sources séparées","Varios vídeos y fuentes separadas","Video multipli e fonti separate","Vários vídeos e fontes separadas","Несколько видео и раздельные источники","فيديوهات متعددة ومصادر منفصلة","多视频及独立音频/幻灯片","複数動画と音声・スライド分離","다중 영상 및 분리 음성/슬라이드","एकाधिक वीडियो व अलग ऑडियो/स्लाइड"],
    "plans.languages":["Kaynak ve çıktı dilleri","Source and output languages","Quell- und Ausgabesprachen","Langues source et sortie","Idiomas de origen y salida","Lingue sorgente e uscita","Idiomas de origem e saída","Языки источника и результата","لغات المصدر والإخراج","源语言与输出语言","入力・出力言語","원본 및 출력 언어","स्रोत और आउटपुट भाषाएँ"],
    "plans.languagesUnit":["dil","languages","Sprachen","langues","idiomas","lingue","idiomas","языков","لغة","种语言","言語","개 언어","भाषाएँ"],
    "plans.outputs":["Transkript, not ve zaman damgası","Transcript, notes, and timestamps","Transkript, Notizen und Zeitmarken","Transcription, notes et horodatages","Transcripción, notas y marcas de tiempo","Trascrizione, note e timestamp","Transcrição, notas e timestamps","Транскрипт, заметки и таймкоды","النص والملاحظات والطوابع الزمنية","转录、笔记与时间戳","文字起こし・ノート・タイムスタンプ","전사, 노트, 타임스탬프","ट्रांसक्रिप्ट, नोट्स और टाइमस्टैम्प"],
    "plans.perMonth":["/ ay","/ month","/ Monat","/ mois","/ mes","/ mese","/ mês","/ месяц","/ شهر","/ 月","/ 月","/ 월","/ माह"],
    "plans.oneTimeShort":["tek ödeme","one time","einmalig","unique","pago único","una tantum","pagamento único","разово","دفعة واحدة","一次性","一回払い","일회성","एक बार"],
    "plans.minutesPerMonth":["dk / ay","min / month","Min. / Monat","min / mois","min / mes","min / mese","min / mês","мин / месяц","دقيقة / شهر","分钟/月","分/月","분/월","मिनट/माह"],
    "plans.minuteUnit":["dakika","minutes","Minuten","minutes","minutos","minuti","minutos","минут","دقائق","分钟","分","분","मिनट"],
    "plans.userUnit":["kullanıcı","users","Nutzer","utilisateurs","usuarios","utenti","usuários","пользователей","مستخدمين","位用户","ユーザー","사용자","उपयोगकर्ता"],
    "plans.popular":["Popüler","Popular","Beliebt","Populaire","Popular","Popolare","Popular","Популярный","الأكثر شيوعًا","热门","人気","인기","लोकप्रिय"],
    "plans.processingSuffix":["işleme","processing","Verarbeitung","traitement","procesamiento","elaborazione","processamento","обработка","معالجة","处理","処理","처리","प्रोसेसिंग"],
    "plans.current":["Mevcut plan","Current plan","Aktueller Tarif","Forfait actuel","Plan actual","Piano attuale","Plano atual","Текущий тариф","الخطة الحالية","当前套餐","現在のプラン","현재 요금제","वर्तमान प्लान"],
    "plans.contact":["Bize ulaş","Contact us","Kontakt","Nous contacter","Contáctanos","Contattaci","Fale conosco","Связаться","تواصل معنا","联系我们","お問い合わせ","문의하기","संपर्क करें"],
    "plans.select":["Planı seç","Choose plan","Tarif wählen","Choisir","Elegir plan","Scegli piano","Escolher plano","Выбрать тариф","اختر الخطة","选择套餐","プランを選択","요금제 선택","प्लान चुनें"],
    "plans.globalPending":["Global kart ve yerel ödeme yöntemleri ödeme sağlayıcısı etkinleştiğinde açılacak. Şimdilik havale için TRY seçebilirsin.","Global cards and local payment methods will open when the payment provider is enabled. For now, select TRY for bank transfer.","Globale Karten und lokale Zahlarten werden mit dem Zahlungsanbieter aktiviert. Wähle vorerst TRY für Überweisung.","Les cartes et moyens locaux seront activés avec le prestataire. Pour l’instant, choisissez TRY pour le virement.","Las tarjetas y métodos locales se activarán con el proveedor. Por ahora elige TRY para transferencia.","Carte e metodi locali saranno attivati con il provider. Per ora scegli TRY per bonifico.","Cartões e métodos locais serão ativados com o provedor. Por enquanto escolha TRY para transferência.","Карты и местные способы откроются после подключения провайдера. Пока выберите TRY для перевода.","ستتوفر البطاقات والطرق المحلية بعد تفعيل مزود الدفع. حاليًا اختر TRY للتحويل.","支付服务启用后将开放银行卡和本地方式。目前转账请选择 TRY。","決済事業者の有効化後にカード等が利用できます。現在は振込用にTRYを選択してください。","결제 제공업체 활성화 후 카드와 현지 결제가 열립니다. 지금은 송금용 TRY를 선택하세요.","भुगतान प्रदाता सक्रिय होने पर कार्ड और स्थानीय तरीके खुलेंगे। अभी ट्रांसफ़र के लिए TRY चुनें।"],
    "plans.quizShort":["quiz sorusu","quiz questions","Quizfragen","questions","preguntas","domande","perguntas","вопросов","أسئلة","测验题","クイズ","퀴즈","क्विज़"],
    "plans.cardsShort":["bilgi kartı","flashcards","Lernkarten","cartes","tarjetas","flashcard","flashcards","карточек","بطاقات","闪卡","カード","플래시카드","फ़्लैशकार्ड"],
    "plans.summaryShort":["özet","summary","Zusammenfassung","résumé","resumen","riepilogo","resumo","конспект","ملخص","摘要","要約","요약","सारांश"],
    "priority.standard":["Standart","Standard","Standard","Standard","Estándar","Standard","Padrão","Стандарт","عادي","标准","標準","표준","मानक"],
    "priority.priority":["Öncelikli","Priority","Priorität","Prioritaire","Prioritario","Prioritario","Prioritário","Приоритет","أولوية","优先","優先","우선","प्राथमिक"],
    "summary.short":["Hızlı","Quick","Kurz","Rapide","Rápido","Rapido","Rápido","Краткий","سريع","快速","クイック","빠른","त्वरित"],
    "summary.standard":["Standart","Standard","Standard","Standard","Estándar","Standard","Padrão","Стандартный","قياسي","标准","標準","표준","मानक"],
    "summary.detailed":["Ayrıntılı","Detailed","Detailliert","Détaillé","Detallado","Dettagliato","Detalhado","Подробный","مفصل","详细","詳細","상세","विस्तृत"],
    "summary.exam":["Sınav","Exam-focused","Prüfungsfokus","Examen","Examen","Esame","Prova","Экзамен","اختبار","考试","試験","시험","परीक्षा"],
    "summary.fiveMinute":["5 dakika","5 minutes","5 Minuten","5 minutes","5 minutos","5 minuti","5 minutos","5 минут","5 دقائق","5分钟","5分","5분","5 मिनट"],
    "common.yes":["Evet","Yes","Ja","Oui","Sí","Sì","Sim","Да","نعم","是","はい","예","हाँ"],
    "common.all":["Tümü","All","Alle","Tous","Todos","Tutti","Todos","Все","الكل","全部","すべて","모두","सभी"],
    "order.pending":["Kontrol bekliyor","Pending review","Prüfung ausstehend","En attente","Pendiente","In attesa","Em análise","На проверке","بانتظار المراجعة","待审核","確認待ち","검토 대기","समीक्षा लंबित"],
    "order.paid":["Aktif","Active","Aktiv","Actif","Activo","Attivo","Ativo","Активен","نشط","已激活","有効","활성","सक्रिय"],
    "state.saving":["Kaydediliyor…","Saving…","Speichern…","Enregistrement…","Guardando…","Salvataggio…","Salvando…","Сохранение…","جارٍ الحفظ…","正在保存…","保存中…","저장 중…","सहेजा जा रहा है…"],
    "auth.passwordMismatch":["Parolalar birbiriyle eşleşmiyor.","Passwords do not match.","Passwörter stimmen nicht überein.","Les mots de passe ne correspondent pas.","Las contraseñas no coinciden.","Le password non coincidono.","As senhas não coincidem.","Пароли не совпадают.","كلمتا المرور غير متطابقتين.","两次密码不一致。","パスワードが一致しません。","비밀번호가 일치하지 않습니다.","पासवर्ड मेल नहीं खाते।"],
    "error.request":["İstek tamamlanamadı.","The request could not be completed.","Die Anfrage konnte nicht abgeschlossen werden.","La demande n’a pas pu aboutir.","No se pudo completar la solicitud.","Impossibile completare la richiesta.","Não foi possível concluir a solicitação.","Не удалось выполнить запрос.","تعذر إكمال الطلب.","无法完成请求。","リクエストを完了できませんでした。","요청을 완료할 수 없습니다.","अनुरोध पूरा नहीं हो सका।"],
    "admin.eyebrow":["Güvenli yönetim","Secure administration","Sichere Verwaltung","Administration sécurisée","Administración segura","Amministrazione sicura","Administração segura","Безопасное управление","إدارة آمنة","安全管理","安全な管理","보안 관리","सुरक्षित प्रशासन"],
    "admin.title":["LectureSift yönetici paneli","LectureSift admin panel","LectureSift-Adminbereich","Administration LectureSift","Panel de LectureSift","Pannello LectureSift","Painel LectureSift","Панель LectureSift","لوحة إدارة LectureSift","LectureSift 管理面板","LectureSift 管理パネル","LectureSift 관리자 패널","LectureSift एडमिन पैनल"],
    "admin.subtitle":["Kullanıcıları ve havale siparişlerini güvenli biçimde incele ve onayla.","Review users and bank-transfer orders securely.","Nutzer und Überweisungen sicher prüfen.","Gérez utilisateurs et virements en toute sécurité.","Revisa usuarios y transferencias de forma segura.","Gestisci utenti e bonifici in sicurezza.","Revise usuários e transferências com segurança.","Безопасно проверяйте пользователей и переводы.","راجع المستخدمين والتحويلات بأمان.","安全审核用户和转账订单。","ユーザーと振込注文を安全に確認します。","사용자와 계좌이체 주문을 안전하게 검토합니다.","उपयोगकर्ताओं और ट्रांसफ़र ऑर्डर की सुरक्षित समीक्षा करें।"],
    "admin.accessTitle":["Yönetici erişimi","Admin access","Adminzugang","Accès administrateur","Acceso de administrador","Accesso amministratore","Acesso administrativo","Доступ администратора","وصول المسؤول","管理员访问","管理者アクセス","관리자 접근","एडमिन एक्सेस"],
    "admin.accessHelp":["Render’da oluşturulan yönetici anahtarını gir. Anahtar tarayıcıya kalıcı olarak kaydedilmez.","Enter the admin token created in Render. It is not stored permanently in the browser.","Gib den Render-Adminschlüssel ein; er wird nicht dauerhaft gespeichert.","Saisissez la clé Render; elle n’est pas stockée durablement.","Introduce la clave de Render; no se guarda permanentemente.","Inserisci la chiave Render; non viene salvata in modo permanente.","Insira a chave do Render; ela não é salva permanentemente.","Введите ключ Render; он не сохраняется постоянно.","أدخل مفتاح Render؛ لن يُحفظ بشكل دائم.","输入 Render 管理密钥；浏览器不会永久保存。","Render の管理キーを入力してください。永続保存されません。","Render 관리자 키를 입력하세요. 영구 저장되지 않습니다.","Render की एडमिन कुंजी डालें; यह स्थायी रूप से सहेजी नहीं जाती।"],
    "admin.token":["Yönetici anahtarı","Admin token","Adminschlüssel","Clé administrateur","Clave de administrador","Chiave amministratore","Chave administrativa","Ключ администратора","مفتاح المسؤول","管理员密钥","管理キー","관리자 키","एडमिन कुंजी"],
    "admin.open":["Paneli aç","Open panel","Panel öffnen","Ouvrir le panneau","Abrir panel","Apri pannello","Abrir painel","Открыть панель","فتح اللوحة","打开面板","パネルを開く","패널 열기","पैनल खोलें"],
    "admin.users":["Kullanıcılar","Users","Nutzer","Utilisateurs","Usuarios","Utenti","Usuários","Пользователи","المستخدمون","用户","ユーザー","사용자","उपयोगकर्ता"],
    "admin.verified":["Doğrulanmış","Verified","Bestätigt","Vérifiés","Verificados","Verificati","Verificados","Подтверждены","موثّقون","已验证","確認済み","인증됨","सत्यापित"],
    "admin.pending":["Bekleyen siparişler","Pending orders","Offene Bestellungen","Commandes en attente","Pedidos pendientes","Ordini in attesa","Pedidos pendentes","Ожидают оплаты","طلبات معلقة","待处理订单","保留中の注文","대기 주문","लंबित ऑर्डर"],
    "admin.subscriptions":["Aktif abonelikler","Active subscriptions","Aktive Abos","Abonnements actifs","Suscripciones activas","Abbonamenti attivi","Assinaturas ativas","Активные подписки","اشتراكات نشطة","有效订阅","有効な契約","활성 구독","सक्रिय सदस्यताएँ"],
    "admin.orders":["Havale siparişleri","Bank-transfer orders","Überweisungsaufträge","Commandes par virement","Pedidos por transferencia","Ordini con bonifico","Pedidos por transferência","Заказы по переводу","طلبات التحويل","转账订单","振込注文","계좌이체 주문","बैंक ट्रांसफ़र ऑर्डर"],
    "admin.refresh":["Yenile","Refresh","Aktualisieren","Actualiser","Actualizar","Aggiorna","Atualizar","Обновить","تحديث","刷新","更新","새로고침","रीफ़्रेश"],
    "admin.usersTitle":["Son kullanıcılar","Recent users","Neueste Nutzer","Utilisateurs récents","Usuarios recientes","Utenti recenti","Usuários recentes","Новые пользователи","أحدث المستخدمين","最近用户","最近のユーザー","최근 사용자","हाल के उपयोगकर्ता"],
    "admin.customer":["Müşteri","Customer","Kunde","Client","Cliente","Cliente","Cliente","Клиент","العميل","客户","顧客","고객","ग्राहक"],
    "admin.plan":["Plan","Plan","Tarif","Forfait","Plan","Piano","Plano","Тариф","الخطة","套餐","プラン","요금제","प्लान"],
    "admin.status":["Durum","Status","Status","Statut","Estado","Stato","Status","Статус","الحالة","状态","状態","상태","स्थिति"],
    "admin.action":["İşlem","Action","Aktion","Action","Acción","Azione","Ação","Действие","الإجراء","操作","操作","작업","कार्रवाई"],
    "admin.approve":["Onayla","Approve","Bestätigen","Approuver","Aprobar","Approva","Aprovar","Подтвердить","موافقة","批准","承認","승인","स्वीकृत करें"],
    "admin.created":["Kayıt tarihi","Created","Erstellt","Créé","Creado","Creato","Criado","Создан","تاريخ الإنشاء","创建时间","登録日","가입일","बनाया गया"],
    "admin.noOrders":["Sipariş bulunamadı.","No orders found.","Keine Bestellungen gefunden.","Aucune commande.","No hay pedidos.","Nessun ordine.","Nenhum pedido.","Заказы не найдены.","لا توجد طلبات.","未找到订单。","注文はありません。","주문이 없습니다.","कोई ऑर्डर नहीं मिला।"],
    "admin.noUsers":["Kullanıcı bulunamadı.","No users found.","Keine Nutzer gefunden.","Aucun utilisateur.","No hay usuarios.","Nessun utente.","Nenhum usuário.","Пользователи не найдены.","لا يوجد مستخدمون.","未找到用户。","ユーザーはいません。","사용자가 없습니다.","कोई उपयोगकर्ता नहीं मिला।"],
    "plan.free":["Ücretsiz","Free","Kostenlos","Gratuit","Gratis","Gratuito","Grátis","Бесплатный","مجاني","免费","無料","무료","मुफ़्त"],
    "plan.credit":["Dakika Paketi","Minute Pack","Minutenpaket","Pack de minutes","Paquete de minutos","Pacchetto minuti","Pacote de minutos","Пакет минут","حزمة دقائق","分钟包","分数パック","시간 팩","मिनट पैक"],
    "plan.lite":["Lite","Lite","Lite","Lite","Lite","Lite","Lite","Lite","Lite","Lite","Lite","Lite","Lite"],
    "plan.plus":["Plus","Plus","Plus","Plus","Plus","Plus","Plus","Plus","Plus","Plus","Plus","Plus","Plus"],
    "plan.pro":["Pro","Pro","Pro","Pro","Pro","Pro","Pro","Pro","Pro","Pro","Pro","Pro","Pro"],
    "plan.max":["Max","Max","Max","Max","Max","Max","Max","Max","Max","Max","Max","Max","Max"],
    "plan.business":["Business","Business","Business","Business","Business","Business","Business","Business","Business","Business","Business","Business","Business"]
  };

  const selected = (() => {
    const saved = localStorage.getItem("lecturesift-ui");
    if (codes.includes(saved)) return saved;
    const browser = (navigator.language || "tr").split("-")[0].toLowerCase();
    return codes.includes(browser) ? browser : "tr";
  })();
  const index = codes.indexOf(selected);
  const t = (key, fallback = "") => rows[key]?.[index] || rows[key]?.[1] || fallback || key;
  const pageCopy = window.LECTURESIFT_PAGE_COPY || {};
  const sourceRows = new Map(Object.entries(pageCopy));
  Object.values(rows).forEach(values => sourceRows.set(values[0], values));
  const exact = source => {
    const values = sourceRows.get(String(source || "").trim());
    return values?.[index] || values?.[1] || source;
  };

  document.documentElement.lang = selected;
  document.documentElement.dir = selected === "ar" ? "rtl" : "ltr";
  document.querySelectorAll("[data-i18n]").forEach(node => { node.textContent = t(node.dataset.i18n, node.textContent); });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(node => { node.placeholder = t(node.dataset.i18nPlaceholder, node.placeholder); });
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const textNodes = [];
  while (walker.nextNode()) textNodes.push(walker.currentNode);
  textNodes.forEach(node => {
    if (["SCRIPT","STYLE","NOSCRIPT"].includes(node.parentElement?.tagName)) return;
    const raw = node.nodeValue || "", value = raw.trim();
    if (!value || selected === "tr" || !sourceRows.has(value)) return;
    node.nodeValue = raw.replace(value, exact(value));
  });
  if (selected !== "tr") {
    document.title = exact(document.title);
    const description = document.querySelector('meta[name="description"]');
    if (description) description.content = exact(description.content);
    document.querySelectorAll("[placeholder],[aria-label],[title]").forEach(node => {
      for (const attribute of ["placeholder", "aria-label", "title"]) {
        if (node.hasAttribute(attribute)) node.setAttribute(attribute, exact(node.getAttribute(attribute)));
      }
    });
  }

  const host = document.querySelector(".auth-topbar,.topbar,.legal-topbar");
  if (host && !host.querySelector(".language-switcher,#uiLanguage")) {
    const picker = document.createElement("select");
    picker.className = "language-switcher";
    picker.setAttribute("aria-label", t("language.label", "Site language"));
    Object.entries(languages).forEach(([code, label]) => picker.add(new Option(label, code)));
    picker.value = selected;
    picker.addEventListener("change", () => { localStorage.setItem("lecturesift-ui", picker.value); location.reload(); });
    const nav = host.querySelector("nav,.top-actions");
    host.insertBefore(picker, nav || host.lastElementChild);
  }

  window.LectureSiftI18n = Object.freeze({language:selected, locale:locales[selected], languages, t, exact, keys:Object.keys(rows)});
})();
