const API="https://lecturesift-backend.onrender.com",TOKEN_KEY="lecturesift-billing-token",ORDER=["free","credit","lite","plus","pro","max","business"];
const COPY={free:["Ücretsiz","Denemek ve kısa dersler için"],credit:["Dakika Paketi","Abonelik olmadan ek kullanım"],lite:["Lite","Düzenli bireysel çalışma"],plus:["Plus","Yoğun ders dönemi ve çoklu kaynaklar"],pro:["Pro","Uzun kayıtlar ve öncelikli işleme"],max:["Max","En yüksek bireysel kapasite"],business:["Business","Ekipler ve kurumlar için"]};
let catalog=null,account=null,currency="TRY";const $=id=>document.getElementById(id);const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function detectedCurrency(){const saved=localStorage.getItem("lecturesift-currency");if(["TRY","USD","EUR","GBP"].includes(saved))return saved;const region=(navigator.language.split("-")[1]||"").toUpperCase();if(region==="TR")return"TRY";if(region==="GB")return"GBP";if(["DE","FR","ES","IT","NL","PT","IE","AT","BE","FI","GR"].includes(region))return"EUR";return"USD"}
function format(amount,code){return new Intl.NumberFormat(code==="TRY"?"tr-TR":"en",{style:"currency",currency:code,maximumFractionDigits:amount%100?2:0}).format(amount/100)}
function showError(message,code="LS-BILL-20"){$("errorMessage").textContent=message;$("errorCode").textContent=code;$("errorBox").hidden=false}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};const token=localStorage.getItem(TOKEN_KEY);if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(`${API}${path}`,{...options,headers,cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(body?.detail?.message||body?.message||"İstek tamamlanamadı."),{code:body?.detail?.code});return body}
function summaries(items=[]){const names={short:"Hızlı",standard:"Standart",detailed:"Ayrıntılı",exam:"Sınav",five_minute:"5 dakika"};return items.map(item=>names[item]||item).join(", ")}
function renderAccount(){if(!account)return;$("authForm").hidden=true;$("accountStatus").hidden=false;$("accountEmail").textContent=account.user.email;$("accountPlan").textContent=account.plan.name||account.plan.code;$("accountRemaining").textContent=`${account.remaining_minutes} dk`}
function renderPlans(){const map=new Map((catalog?.plans||[]).map(plan=>[plan.code,plan]));$("plansGrid").innerHTML=ORDER.map(code=>{const p=map.get(code);if(!p)return"";const ent=p.entitlements||{},price=p.display_price||p.manual_price,current=account?.plan?.code===code;const priceText=price?format(price.amount_minor,price.currency||currency):(code==="free"?format(0,currency):"Teklif");const suffix=p.kind==="subscription"?"/ ay":p.kind==="one_time"?"tek ödeme":"";return`<article class="plan-card ${p.featured?"featured":""}">${p.featured?'<span class="plan-badge">Popüler</span>':""}<h3>${esc(COPY[code][0])}</h3><p>${esc(COPY[code][1])}</p><div class="plan-price">${esc(priceText)} <small>${suffix}</small></div><ul class="plan-features"><li>${p.minutes_per_month?`${p.minutes_per_month.toLocaleString("tr-TR")} dk / ay`:`${(p.credit_minutes||0).toLocaleString("tr-TR")} dakika`}</li><li>${ent.quiz_questions??"∞"} quiz sorusu</li><li>${ent.flashcards??"∞"} bilgi kartı</li><li>${esc(summaries(ent.summary_profiles))} özet</li><li>${esc((ent.export_formats||[]).join(", ").toUpperCase())}</li><li>${p.priority==="priority"?"Öncelikli":"Standart"} işleme</li></ul><button class="plan-action" data-plan="${esc(code)}" ${current||code==="free"||code==="business"?"disabled":""}>${current?"Mevcut plan":code==="business"?"Bize ulaş":"Planı seç"}</button></article>`}).join("");document.querySelectorAll(".plan-action[data-plan]").forEach(button=>button.onclick=()=>buy(button.dataset.plan))}
async function buy(planCode){if(!localStorage.getItem(TOKEN_KEY)){location.href=`/login.html?next=${encodeURIComponent("/plans.html")}`;return}if(currency!=="TRY"){showError("Global kart ödemeleri ödeme sağlayıcısı etkinleştiğinde açılacak. Şimdilik havale için TRY seçebilirsin.");return}try{const plan=catalog.plans.find(item=>item.code===planCode);const body=await api("/billing/manual-transfer/orders",{method:"POST",body:JSON.stringify({plan_code:planCode,interval:plan?.kind==="one_time"?"one_time":"monthly"})});const order=body.order;$("transferReference").textContent=order.reference;$("transferAmount").textContent=format(order.amount_minor,order.currency||"TRY");$("transferIban").textContent=order.bank.iban.replace(/(.{4})/g,"$1 ").trim();$("transferHolder").textContent=order.bank.account_holder;$("transferInstruction").textContent=order.instruction;$("transferSupport").href=`mailto:${encodeURIComponent(order.support_email)}?subject=${encodeURIComponent(`LectureSift ${order.reference}`)}`;$("transferPanel").hidden=false;$("transferPanel").scrollIntoView({behavior:"smooth"})}catch(error){showError(error.message,error.code)}}
async function load(){currency=detectedCurrency();$("billingCurrency").value=currency;try{catalog=await api(`/billing/plans?currency=${encodeURIComponent(currency)}`);try{account=(await api("/billing/me")).account}catch{}renderAccount();renderPlans()}catch(error){showError(error.message,error.code)}}
$("billingCurrency").addEventListener("change",()=>{currency=$("billingCurrency").value;localStorage.setItem("lecturesift-currency",currency);load()});$("closeError").onclick=()=>$("errorBox").hidden=true;load();
