services:
  - type: web
    name: lecturesift-backend
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: INSTAGRAM_ACCESS_TOKEN
        sync: false
      - key: INSTAGRAM_ACCOUNT_ID
        sync: false
      - key: INSTAGRAM_APP_SECRET
        sync: false
      - key: INSTAGRAM_ADMIN_TOKEN
        sync: false

