#!/usr/bin/env python3
"""Derive root-only, least-privilege service env files from runtime.env.

The populated runtime file is the root-owned source of truth.  It is never
mounted into a container.  This script copies application assignments
verbatim into an API file while always excluding host-only backup credentials,
and applies explicit allowlists for the worker and Instagram job. Unknown
values therefore cannot silently cross a service boundary.
"""

from __future__ import annotations

import argparse
import os
import re
import stat
import tempfile
from collections import OrderedDict
from pathlib import Path
from typing import Iterable, Mapping


ASSIGNMENT = re.compile(r"^[ \t]*(?:export[ \t]+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$")
GENERATED_HEADER = (
    "# Generated by deploy/generate_role_envs.py from the root-only runtime.env.\n"
    "# Do not edit or copy this file into the repository.\n"
)

WORKER_KEYS = frozenset(
    {
        "CELERY_BROKER_URL",
        "REDIS_URL",
        "OPENAI_API_KEY",
        "S3_ENDPOINT_URL",
        "S3_REGION",
        "S3_BUCKET",
        "S3_ACCESS_KEY_ID",
        "S3_SECRET_ACCESS_KEY",
        "LECTURESIFT_WORK_DIR",
        "LECTURESIFT_REQUIRE_POSTGRES",
        "LECTURESIFT_REQUIRE_DURABLE_PROCESSING",
        "LECTURESIFT_MAINTENANCE_MODE",
        "LECTURESIFT_CELERY_VISIBILITY_TIMEOUT_SECONDS",
        "LECTURESIFT_MAX_VIDEO_BYTES",
        "LECTURESIFT_MAX_SOURCE_FILES",
        "LECTURESIFT_MAX_DOCUMENT_BYTES",
        "LECTURESIFT_MAX_DOCUMENT_PAGES",
        "LECTURESIFT_MAX_DOCUMENT_CHARACTERS",
        "LECTURESIFT_DOCUMENT_WORDS_PER_CREDIT_MINUTE",
        "LECTURESIFT_JOB_TTL_SECONDS",
        "LECTURESIFT_HOST_DISK_RESERVE_BYTES",
        "LECTURESIFT_MAX_JOB_WORK_BYTES",
        "LECTURESIFT_TRANSCRIPTION_PARALLELISM",
        "LECTURESIFT_MEDIA_PREP_PARALLELISM",
        "LECTURESIFT_SLIDE_ANALYSIS_PARALLELISM",
        "LECTURESIFT_SLIDE_EXPORT_PARALLELISM",
        "LECTURESIFT_TRANSLATION_PARALLELISM",
        "LECTURESIFT_STUDY_PACK_PARALLELISM",
        "LECTURESIFT_SOURCE_DOWNLOAD_PARALLELISM",
        "LECTURESIFT_STORAGE_TRANSFER_PARALLELISM",
        "LECTURESIFT_STORAGE_FILE_TRANSFER_CONCURRENCY",
        "LECTURESIFT_DURATION_PROBE_PARALLELISM",
        "LECTURESIFT_ARTIFACT_EXPORT_PARALLELISM",
        "LECTURESIFT_PRECISE_TRANSCRIPT_TIMESTAMPS",
        "LECTURESIFT_OCR_ENABLED",
        "LECTURESIFT_OCR_COMMAND",
        "LECTURESIFT_OCR_DPI",
        "LECTURESIFT_OCR_MAX_PAGES",
        "LECTURESIFT_OCR_PARALLELISM",
        "LECTURESIFT_OCR_PAGE_TIMEOUT_SECONDS",
        "LECTURESIFT_OCR_MIN_NATIVE_CHARACTERS",
        "LECTURESIFT_OCR_ESTIMATED_WORDS_PER_PAGE",
        # The worker enforces the anonymous processing quota as a final guard.
        "LECTURESIFT_GUEST_TRIAL_MINUTES",
        # Cost planning inputs are not credentials. Keep this list explicit so
        # a future secret with a COST-like name cannot cross the boundary.
        "LECTURESIFT_COST_USD_TRY_FALLBACK",
        "LECTURESIFT_COST_RENDER_MONTHLY_USD",
        "LECTURESIFT_COST_RENDER_CONFIRMED",
        "LECTURESIFT_COST_NETLIFY_MONTHLY_USD",
        "LECTURESIFT_COST_NETLIFY_CONFIRMED",
        "LECTURESIFT_COST_RESEND_MONTHLY_USD",
        "LECTURESIFT_COST_RESEND_CONFIRMED",
        "LECTURESIFT_COST_DOMAIN_ANNUAL_USD",
        "LECTURESIFT_COST_DOMAIN_CONFIRMED",
        "LECTURESIFT_COST_OTHER_MONTHLY_USD",
        "LECTURESIFT_COST_OTHER_CONFIRMED",
    }
)

INSTAGRAM_KEYS = frozenset(
    {
        "PUBLIC_BASE_URL",
        "INSTAGRAM_ACCESS_TOKEN",
        "INSTAGRAM_ACCOUNT_ID",
        "INSTAGRAM_APP_SECRET",
        "INSTAGRAM_GRAPH_API_VERSION",
        "INSTAGRAM_DAILY_AUTOMATION_ENABLED",
        "INSTAGRAM_DAILY_MEDIA_TYPE",
    }
)

WORKER_REQUIRED = frozenset(
    {
        "LECTURESIFT_WORKER_DATABASE_URL",
        "CELERY_BROKER_URL",
        "REDIS_URL",
        "OPENAI_API_KEY",
        "S3_ENDPOINT_URL",
        "S3_BUCKET",
        "S3_ACCESS_KEY_ID",
        "S3_SECRET_ACCESS_KEY",
        "LECTURESIFT_WORK_DIR",
        "LECTURESIFT_REQUIRE_POSTGRES",
        "LECTURESIFT_REQUIRE_DURABLE_PROCESSING",
    }
)

INSTAGRAM_ENABLED_REQUIRED = frozenset(
    {
        "INSTAGRAM_ACCESS_TOKEN",
        "INSTAGRAM_ACCOUNT_ID",
        "INSTAGRAM_APP_SECRET",
        "INSTAGRAM_GRAPH_API_VERSION",
        "INSTAGRAM_DAILY_AUTOMATION_ENABLED",
        "INSTAGRAM_DAILY_MEDIA_TYPE",
    }
)

# Application credentials are intentionally enumerated. A future secret-like
# name that is not reviewed here blocks generation instead of silently entering
# the internet-facing API container.
API_SENSITIVE_KEYS = frozenset(
    {
        "ADMIN_ADMIN",
        "BILLING_LEGACY_SESSION_SECRET_HEX",
        "BILLING_SESSION_SECRET",
        "CELERY_BROKER_URL",
        "DATABASE_URL",
        "INSTAGRAM_ACCESS_TOKEN",
        "INSTAGRAM_ADMIN_TOKEN",
        "INSTAGRAM_APP_SECRET",
        "IYZICO_API_KEY",
        "IYZICO_SECRET_KEY",
        "OPENAI_API_KEY",
        "PAYMENT_TOKEN_BINDING_LEGACY_SECRET",
        "PAYMENT_TOKEN_BINDING_SECRET",
        "PAYTR_MERCHANT_KEY",
        "PAYTR_MERCHANT_SALT",
        "REDIS_URL",
        "RESEND_API_KEY",
        "S3_ACCESS_KEY_ID",
        "S3_SECRET_ACCESS_KEY",
        "SMTP_PASSWORD",
    }
)
SENSITIVE_NAME_MARKERS = (
    "API_KEY",
    "ACCESS_KEY",
    "_SECRET",
    "_TOKEN",
    "_PASSWORD",
    "_PRIVATE_KEY",
    "_CREDENTIAL",
)
HOST_ONLY_PREFIXES = (
    "AWS_",
    "BACKUP_",
    "CLOUDFLARE_",
    "LECTURESIFT_REHEARSAL_",
    "OVH_",
    "RESTIC_",
    "SOURCE_",
)

# Backup repository access and encryption credentials are host-only even if
# somebody accidentally places them in the application master file. The API
# otherwise receives the complete application configuration.
HOST_ONLY_KEYS = frozenset(
    {
        # The API gets DATABASE_URL while the worker source URL is rewritten
        # to DATABASE_URL only in worker.env.  Never expose the second login
        # to the internet-facing API container.
        "LECTURESIFT_WORKER_DATABASE_URL",
        # Build identity comes only from the image layer/release helper. A
        # master runtime value must never override what `/health` reports.
        "LECTURESIFT_BUILD_REVISION",
        "LECTURESIFT_EXPECTED_BUILD_REVISION",
        "LECTURESIFT_RELEASE_ENV_FILE",
        "RENDER_GIT_COMMIT",
        # Global work-volume budgets are host-only. Per-job/reserve values are
        # also passed to API/worker because they enforce each write/stage.
        "LECTURESIFT_MAX_API_WORKSPACE_BYTES",
        "LECTURESIFT_MAX_WORKER_WORKSPACE_BYTES",
        "RESTIC_REPOSITORY",
        "RESTIC_PASSWORD",
        "RESTIC_AWS_ACCESS_KEY_ID",
        "RESTIC_AWS_SECRET_ACCESS_KEY",
    }
)


class RoleEnvironmentError(RuntimeError):
    """Raised when an env source or generated role file is unsafe."""


def parse_runtime(path: Path) -> OrderedDict[str, str]:
    """Return key -> original RHS while rejecting ambiguous dotenv syntax."""

    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        raise RoleEnvironmentError(f"cannot read runtime environment: {path}") from exc
    if "\x00" in text:
        raise RoleEnvironmentError("runtime environment contains a NUL byte")

    assignments: OrderedDict[str, str] = OrderedDict()
    for line_number, raw_line in enumerate(text.splitlines(), 1):
        if not raw_line.strip() or raw_line.lstrip().startswith("#"):
            continue
        match = ASSIGNMENT.fullmatch(raw_line)
        if not match:
            raise RoleEnvironmentError(
                f"unsupported runtime environment syntax at line {line_number}"
            )
        key, rhs = match.groups()
        if key in assignments:
            raise RoleEnvironmentError(f"duplicate runtime environment key: {key}")
        if key == "LECTURESIFT_RECOVERY_BOOTSTRAP_OVERRIDE":
            raise RoleEnvironmentError(
                "LECTURESIFT_RECOVERY_BOOTSTRAP_OVERRIDE must stay outside runtime.env"
            )
        assignments[key] = rhs
    if not assignments:
        raise RoleEnvironmentError("runtime environment has no assignments")
    return assignments


def _worker_allowed(key: str) -> bool:
    return key in WORKER_KEYS


def _host_only(key: str) -> bool:
    return key in HOST_ONLY_KEYS or key.startswith(HOST_ONLY_PREFIXES)


def _api_allowed(key: str) -> bool:
    if _host_only(key):
        return False
    if any(marker in key for marker in SENSITIVE_NAME_MARKERS):
        if key not in API_SENSITIVE_KEYS:
            raise RoleEnvironmentError(
                f"unreviewed sensitive runtime key cannot enter the API role: {key}"
            )
    return True


def _literal_value(assignments: Mapping[str, str], key: str) -> str:
    """Return a simple dotenv literal without evaluating shell syntax."""

    raw = assignments.get(key, "").strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in {"'", '"'}:
        raw = raw[1:-1]
    return raw


def render_role(assignments: Mapping[str, str], role: str) -> str:
    """Render one deterministic role file from the parsed master assignments."""

    if role == "api":
        keys: Iterable[str] = (key for key in assignments if _api_allowed(key))
        required: frozenset[str] = frozenset()
    elif role == "worker":
        keys = (key for key in assignments if _worker_allowed(key))
        required = WORKER_REQUIRED
    elif role == "instagram":
        enabled = _literal_value(assignments, "INSTAGRAM_DAILY_AUTOMATION_ENABLED").casefold()
        if enabled not in {"true", "false"}:
            raise RoleEnvironmentError(
                "INSTAGRAM_DAILY_AUTOMATION_ENABLED must be exactly true or false"
            )
        if enabled == "false":
            return (
                GENERATED_HEADER
                + "INSTAGRAM_DAILY_AUTOMATION_ENABLED="
                + assignments["INSTAGRAM_DAILY_AUTOMATION_ENABLED"]
                + "\n"
            )
        keys = (key for key in assignments if key in INSTAGRAM_KEYS)
        required = INSTAGRAM_ENABLED_REQUIRED
    else:
        raise RoleEnvironmentError(f"unknown role: {role}")

    missing = sorted(required.difference(assignments))
    if missing:
        raise RoleEnvironmentError(
            f"runtime environment is missing {role} keys: {', '.join(missing)}"
        )
    lines = [GENERATED_HEADER.rstrip("\n")]
    if role == "worker":
        lines.append(f"DATABASE_URL={assignments['LECTURESIFT_WORKER_DATABASE_URL']}")
    lines.extend(f"{key}={assignments[key]}" for key in keys)
    return "\n".join(lines) + "\n"


def _check_private_file(path: Path, *, label: str) -> None:
    try:
        details = path.lstat()
    except OSError as exc:
        raise RoleEnvironmentError(f"missing {label}: {path}") from exc
    if stat.S_ISLNK(details.st_mode) or not stat.S_ISREG(details.st_mode):
        raise RoleEnvironmentError(f"{label} must be a regular non-symlink file: {path}")
    if details.st_uid != 0:
        raise RoleEnvironmentError(f"{label} must be owned by root: {path}")
    if stat.S_IMODE(details.st_mode) not in {0o400, 0o600}:
        raise RoleEnvironmentError(f"{label} must have mode 0400 or 0600: {path}")


def _check_private_directory(path: Path) -> None:
    try:
        details = path.lstat()
    except OSError as exc:
        raise RoleEnvironmentError(f"missing role environment directory: {path}") from exc
    if stat.S_ISLNK(details.st_mode) or not stat.S_ISDIR(details.st_mode):
        raise RoleEnvironmentError(f"role environment parent must be a real directory: {path}")
    if details.st_uid != 0 or stat.S_IMODE(details.st_mode) & 0o022:
        raise RoleEnvironmentError(
            f"role environment parent must be root-owned and not group/other writable: {path}"
        )
    try:
        if path.resolve(strict=True) != path.absolute():
            raise RoleEnvironmentError(f"role environment parent resolves through a symlink: {path}")
    except OSError as exc:
        raise RoleEnvironmentError(f"cannot resolve role environment parent: {path}") from exc


def _open_lock(directory: Path) -> int:
    import fcntl

    flags = os.O_RDWR | os.O_CREAT
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    try:
        descriptor = os.open(directory / ".role-env.lock", flags, 0o600)
    except OSError as exc:
        raise RoleEnvironmentError("cannot safely open the role environment lock") from exc
    details = os.fstat(descriptor)
    if details.st_uid != 0 or not stat.S_ISREG(details.st_mode):
        os.close(descriptor)
        raise RoleEnvironmentError("role environment lock is not a root-owned regular file")
    os.fchmod(descriptor, 0o600)
    fcntl.flock(descriptor, fcntl.LOCK_EX)
    return descriptor


def _write_temp(destination: Path, content: str) -> Path:
    descriptor, name = tempfile.mkstemp(prefix=f".{destination.name}.", dir=destination.parent)
    temporary = Path(name)
    handle_open = False
    try:
        os.fchmod(descriptor, 0o600)
        os.fchown(descriptor, 0, 0)
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle_open = True
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
    except BaseException:
        if not handle_open:
            os.close(descriptor)
        temporary.unlink(missing_ok=True)
        raise
    return temporary


def materialize(
    source: Path,
    destinations: Mapping[str, Path],
    *,
    check_only: bool,
) -> None:
    """Atomically create role files or prove that every file is exact and private."""

    if os.geteuid() != 0:
        raise RoleEnvironmentError("role environment generation must run as root")
    if not source.is_absolute() or any(not path.is_absolute() for path in destinations.values()):
        raise RoleEnvironmentError("runtime and role environment paths must be absolute")
    _check_private_file(source, label="runtime environment")
    resolved_source = source.resolve(strict=True)
    if len({str(path.absolute()) for path in destinations.values()}) != len(destinations):
        raise RoleEnvironmentError("role environment destinations must be distinct")
    for path in destinations.values():
        _check_private_directory(path.parent)
        if path.absolute() == resolved_source:
            raise RoleEnvironmentError("a role environment cannot overwrite runtime.env")
        if path.exists() or path.is_symlink():
            _check_private_file(path, label="role environment")

    assignments = parse_runtime(source)
    expected = {role: render_role(assignments, role) for role in destinations}
    lock_directories = {path.parent for path in destinations.values()}
    if len(lock_directories) != 1:
        raise RoleEnvironmentError("all role environment files must share one private directory")
    lock_fd = _open_lock(next(iter(lock_directories)))
    temporary_files: dict[str, Path] = {}
    try:
        if check_only:
            for role, destination in destinations.items():
                _check_private_file(destination, label=f"{role} environment")
                try:
                    actual = destination.read_text(encoding="utf-8")
                except (OSError, UnicodeError) as exc:
                    raise RoleEnvironmentError(
                        f"cannot read {role} environment: {destination}"
                    ) from exc
                if actual != expected[role]:
                    raise RoleEnvironmentError(
                        f"{role} environment is stale or contains unauthorized keys"
                    )
            return

        for role, destination in destinations.items():
            temporary_files[role] = _write_temp(destination, expected[role])
        for role, destination in destinations.items():
            os.replace(temporary_files.pop(role), destination)
            # _write_temp applied ownership and mode through the already-open
            # descriptor. rename(2) preserves both without relying on optional
            # path-level follow_symlinks support (which is absent on some Linux
            # Python builds). Verify the installed inode before proceeding.
            _check_private_file(destination, label=f"{role} environment")
    finally:
        for temporary in temporary_files.values():
            temporary.unlink(missing_ok=True)
        os.close(lock_fd)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate exact content and permissions without changing role files",
    )
    args = parser.parse_args()
    source = Path(os.environ.get("LECTURESIFT_ENV_FILE", "/etc/lecturesift/runtime.env"))
    destinations = {
        "api": Path(os.environ.get("LECTURESIFT_API_ENV_FILE", "/etc/lecturesift/api.env")),
        "worker": Path(
            os.environ.get("LECTURESIFT_WORKER_ENV_FILE", "/etc/lecturesift/worker.env")
        ),
        "instagram": Path(
            os.environ.get(
                "LECTURESIFT_INSTAGRAM_ENV_FILE", "/etc/lecturesift/instagram.env"
            )
        ),
    }
    try:
        materialize(source, destinations, check_only=args.check)
    except RoleEnvironmentError as exc:
        parser.exit(1, f"Role environment validation failed: {exc}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
