from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def replace(path: str, old: str, new: str, *, count: int = 1) -> None:
    target = ROOT / path
    text = target.read_text(encoding="utf-8")
    found = text.count(old)
    if found != count:
        raise RuntimeError(f"{path}: expected {count}, found {found}: {old[:120]!r}")
    target.write_text(text.replace(old, new), encoding="utf-8")


# Main page markup.
replace("frontend/index.html", '<link rel="stylesheet" href="./styles.css">\n', '<link rel="stylesheet" href="./styles.css">\n  <link rel="stylesheet" href="./commerce.css?v=1">\n')
replace("frontend/index.html", '<div class="trust-row"><span>✓ 60 dakika ücretsiz</span><span>✓ 13 dil</span><span>✓ PDF, Word ve TXT</span></div>', '<div class="trust-row"><span>✓ Ücretsiz sınırlı önizleme</span><span>✓ 13 dil</span><span>✓ İndirme Mini paketle açılır</span></div>')
replace(
    "frontend/index.html",
    '          <label id="translateControl" class="toggle-control"><span><b data-i18n="translateTitle">Transkripti çevir</b><small id="translateHelp" data-i18n="translateHelp">Orijinali de korunur</small></span><input id="translateTranscript" type="checkbox" checked><i aria-hidden="true"></i></label>\n',
    '          <label id="translateControl" class="toggle-control"><span><b data-i18n="translateTitle">Transkripti çevir</b><small id="translateHelp" data-i18n="translateHelp">Orijinali de korunur</small></span><input id="translateTranscript" type="checkbox" checked><i aria-hidden="true"></i></label>\n          <label id="visualTranslationControl" class="toggle-control visual-translation-control"><span><b data-i18n="visualTranslateTitle">Slayt ve ekran yazılarını çevir</b><small id="visualTranslateHelp" class="feature-lock-note" data-i18n="visualTranslateHelp">Orijinal görseller korunur · Mini ve ücretli planlar</small></span><input id="translateVisualText" type="checkbox"><i aria-hidden="true"></i></label>\n',
)
replace("frontend/index.html", 'Havale ödemeleri ödeme kontrolünden sonra etkinleştirilir. PayTR açıldığında kart ve otomatik yenileme eklenecek.', 'Aylık veya yıllık plan seç; yıllık abonelikte iki ay avantaj sağlanır. Kart ve havale seçenekleri ödeme ekranında gösterilir.')
replace(
    "frontend/index.html",
    '      <div class="result-tabs" role="tablist">\n',
    '      <div id="downloadLockPanel" class="download-lock-panel" hidden><div><h3 data-i18n="downloadLockedTitle">Önizleme hazır, indirme kilitli</h3><p data-i18n="downloadLockedText">Tam sonucu ve ZIP/PDF/Word/TXT dosyalarını açmak için Mini paket veya ücretli plan seç.</p></div><a href="/plans.html?plan=mini" data-i18n="unlockDownload">İndirmeyi aç</a></div>\n      <div class="result-tabs" role="tablist">\n',
)
replace("frontend/index.html", '<script src="./app.js?v=5"></script>\n<script src="/rollout.js?v=1"></script>', '<script src="./app.js?v=6"></script>\n<script src="/rollout.js?v=2"></script>')

# Main application copy and plan fallbacks.
replace("frontend/app.js", '  quizCount: "Quiz questions", cardCount: "Flashcards", translateTitle: "Translate transcript", translateHelp: "The original is preserved", analyze: "Analyze lecture",\n', '  quizCount: "Quiz questions", cardCount: "Flashcards", translateTitle: "Translate transcript", translateHelp: "The original is preserved", visualTranslateTitle: "Translate text inside slides and screens", visualTranslateHelp: "Original images are preserved · Mini and paid plans", analyze: "Analyze lecture",\n')
replace("frontend/app.js", '  pendingApproval: "Pending review", loginRequired: "Sign in before choosing a plan.", accountReady: "Account is ready."\n', '  pendingApproval: "Pending review", loginRequired: "Sign in before choosing a plan.", accountReady: "Account is ready.", downloadLockedTitle: "Preview ready, downloads locked", downloadLockedText: "Choose Mini or a paid plan to unlock the full result and ZIP/PDF/Word/TXT files.", unlockDownload: "Unlock downloads", previewOnly: "Limited preview"\n')
replace("frontend/app.js", '  quizCount: "Quiz sorusu", cardCount: "Bilgi kartı", translateTitle: "Transkripti çevir", translateHelp: "Orijinali de korunur", analyze: "Dersi analiz et",\n', '  quizCount: "Quiz sorusu", cardCount: "Bilgi kartı", translateTitle: "Transkripti çevir", translateHelp: "Orijinali de korunur", visualTranslateTitle: "Slayt ve ekran yazılarını çevir", visualTranslateHelp: "Orijinal görseller korunur · Mini ve ücretli planlar", analyze: "Dersi analiz et",\n')
replace("frontend/app.js", '  pendingApproval: "Kontrol bekliyor", loginRequired: "Plan seçmeden önce giriş yap.", accountReady: "Hesabın hazır."\n', '  pendingApproval: "Kontrol bekliyor", loginRequired: "Plan seçmeden önce giriş yap.", accountReady: "Hesabın hazır.", downloadLockedTitle: "Önizleme hazır, indirme kilitli", downloadLockedText: "Tam sonucu ve ZIP/PDF/Word/TXT dosyalarını açmak için Mini paket veya ücretli plan seç.", unlockDownload: "İndirmeyi aç", previewOnly: "Sınırlı önizleme"\n')
replace("frontend/app.js", '    free: ["Ücretsiz", "LectureSift\'i denemek ve kısa dersleri işlemek için.", "60 dk / ay"],\n    credit: ["Dakika Paketi", "Abonelik olmadan ek işlem hakkı.", "180 dakika"],\n', '    free: ["Ücretsiz", "Dersi işle ve sınırlı önizle; dosya indirme kapalıdır.", "60 dk / ay · indirme yok"],\n    mini: ["Mini", "İlk indirme veya tek kısa ders için sembolik paket.", "60 dakika · indirme açık"],\n    credit: ["Dakika Paketi", "Abonelik olmadan ek işlem ve indirme hakkı.", "180 dakika"],\n')
replace("frontend/app.js", '    free: ["Free", "Try LectureSift and process short lectures.", "60 min / month"],\n    credit: ["Minute Pack", "Extra processing without a subscription.", "180 minutes"],\n', '    free: ["Free", "Process a lecture and see a limited preview; downloads are locked.", "60 min / month · no downloads"],\n    mini: ["Mini", "A symbolic first-download or one-short-lecture pack.", "60 minutes · downloads on"],\n    credit: ["Minute Pack", "Extra processing and downloads without a subscription.", "180 minutes"],\n')
replace("frontend/app.js", 'const PLAN_ORDER = ["free", "credit", "lite", "plus", "pro", "max", "business"];\n', 'const PLAN_ORDER = ["free", "mini", "credit", "lite", "plus", "pro", "max", "business"];\n')
replace(
    "frontend/app.js",
    '  free: ["free", 60, 10, 20, ["pdf"], ["short", "standard"], "standard", false],\n  credit: ["one_time", 180, 20, 40, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "standard", false],\n',
    '  free: ["free", 60, 10, 20, [], ["short", "standard"], "standard", false, false, false],\n  mini: ["one_time", 60, 20, 40, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "standard", false, true, true],\n  credit: ["one_time", 180, 20, 40, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "standard", false, true, true],\n',
)
replace("frontend/app.js", '  lite: ["subscription", 600, 20, 40, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "standard", false],\n  plus: ["subscription", 2400, 30, 60, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "standard", true],\n  pro: ["subscription", 6000, 30, 60, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "priority", false],\n  max: ["subscription", 15000, 30, 60, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "priority", false],\n  business: ["quote", null, null, null, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "priority", false],\n', '  lite: ["subscription", 600, 20, 40, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "standard", false, true, true],\n  plus: ["subscription", 2400, 30, 60, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "standard", true, true, true],\n  pro: ["subscription", 6000, 30, 60, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "priority", false, true, true],\n  max: ["subscription", 15000, 30, 60, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "priority", false, true, true],\n  business: ["quote", null, null, null, ["pdf", "docx", "txt"], ["short", "standard", "detailed", "exam", "five_minute"], "priority", false, true, true],\n')
replace("frontend/app.js", '  TRY: [0,19900,34900,69900,129900,249900,null], USD: [0,500,900,1800,3300,6300,null],\n  EUR: [0,500,900,1700,3100,5900,null], GBP: [0,400,800,1500,2700,5200,null],\n  CAD: [0,700,1200,2500,4500,8500,null], AUD: [0,800,1400,2800,5200,9900,null],\n  NZD: [0,900,1600,3100,5700,10900,null], JPY: [0,800,1400,2800,5000,9500,null],\n  KRW: [0,7000,13000,25000,47000,89000,null], CNY: [0,3600,6500,12900,23900,45900,null],\n  INR: [0,39900,74900,149900,279900,529900,null], BRL: [0,2500,4500,8900,16900,31900,null],\n  MXN: [0,9900,17900,34900,64900,124900,null], CHF: [0,500,800,1600,3000,5700,null],\n  SEK: [0,5500,9900,19900,36900,69900,null], NOK: [0,5900,10900,21900,39900,76900,null],\n  DKK: [0,3500,6500,12900,22900,44900,null], PLN: [0,2000,3600,7200,13200,25200,null],\n  AED: [0,1900,3300,6600,12100,23100,null], SAR: [0,1900,3400,6800,12400,23600,null],\n  SGD: [0,700,1200,2400,4500,8500,null], HKD: [0,3900,7000,14000,26000,49000,null],\n', '  TRY: [0,4900,14900,34900,69900,129900,249900,null], USD: [0,200,500,900,1800,3300,6300,null],\n  EUR: [0,200,500,900,1700,3100,5900,null], GBP: [0,150,400,800,1500,2700,5200,null],\n  CAD: [0,300,700,1200,2500,4500,8500,null], AUD: [0,300,800,1400,2800,5200,9900,null],\n  NZD: [0,350,900,1600,3100,5700,10900,null], JPY: [0,300,800,1400,2800,5000,9500,null],\n  KRW: [0,3000,7000,13000,25000,47000,89000,null], CNY: [0,1500,3600,6500,12900,23900,45900,null],\n  INR: [0,14900,39900,74900,149900,279900,529900,null], BRL: [0,1000,2500,4500,8900,16900,31900,null],\n  MXN: [0,3900,9900,17900,34900,64900,124900,null], CHF: [0,200,500,800,1600,3000,5700,null],\n  SEK: [0,2200,5500,9900,19900,36900,69900,null], NOK: [0,2400,5900,10900,21900,39900,76900,null],\n  DKK: [0,1500,3500,6500,12900,22900,44900,null], PLN: [0,800,2000,3600,7200,13200,25200,null],\n  AED: [0,800,1900,3300,6600,12100,23100,null], SAR: [0,800,1900,3400,6800,12400,23600,null],\n  SGD: [0,300,700,1200,2400,4500,8500,null], HKD: [0,1600,3900,7000,14000,26000,49000,null],\n')
replace("frontend/app.js", '    const [kind, minutes, quiz, cards, formats, summaries, priority, featured] = PLAN_FALLBACK[code];\n', '    const [kind, minutes, quiz, cards, formats, summaries, priority, featured, downloadEnabled, visualTranslation] = PLAN_FALLBACK[code];\n')
replace("frontend/app.js", '    return {code, kind, minutes, priority, featured, display_price:amount == null ? null : {currency:selected, amount_minor:amount}, entitlements:{minutes, quiz_questions:quiz, flashcards:cards, export_formats:formats, summary_profiles:summaries, priority}};\n', '    const interval_prices = kind === "subscription" && amount != null ? {monthly:{currency:selected,amount_minor:amount},annual:{currency:selected,amount_minor:amount * 10}} : (kind === "one_time" && amount != null ? {one_time:{currency:selected,amount_minor:amount}} : {});\n    return {code, kind, minutes, priority, featured, download_enabled:downloadEnabled, visual_translation:visualTranslation, display_price:amount == null ? null : {currency:selected, amount_minor:amount}, interval_prices, entitlements:{minutes, quiz_questions:quiz, flashcards:cards, export_formats:formats, summary_profiles:summaries, priority, download_enabled:downloadEnabled, visual_translation:visualTranslation}};\n')
replace("frontend/app.js", '<li>${escapeHtml((entitlements.export_formats || []).join(", ").toUpperCase())}</li>', '<li>${entitlements.download_enabled === false ? (currentLanguage === "tr" ? "Sınırlı önizleme · indirme yok" : "Limited preview · no downloads") : escapeHtml((entitlements.export_formats || []).join(", ").toUpperCase())}</li>')
replace("frontend/app.js", '  document.querySelectorAll(".plan-action[data-plan]").forEach(button => button.onclick = () => createTransferOrder(button.dataset.plan));\n', '  document.querySelectorAll(".plan-action[data-plan]").forEach(button => button.onclick = () => { location.href = `/plans.html?plan=${encodeURIComponent(button.dataset.plan)}`; });\n')
replace("frontend/app.js", '  data.append("translate_transcript", $("translateTranscript").checked ? "true" : "false");\n', '  data.append("translate_transcript", $("translateTranscript").checked ? "true" : "false");\n  data.append("translate_visual_text", $("translateVisualText")?.checked ? "true" : "false");\n')
replace(
    "frontend/app.js",
    '  $("translateTranscript").disabled = same;\n  if (same) $("translateTranscript").checked = false;\n  $("translateHelp").textContent = same ? t("sameLanguageHelp") : t("translateHelp");\n',
    '  $("translateTranscript").disabled = same;\n  if (same) $("translateTranscript").checked = false;\n  $("translateHelp").textContent = same ? t("sameLanguageHelp") : t("translateHelp");\n  if ($("translateVisualText")) {\n    $("translateVisualText").disabled = same;\n    if (same) $("translateVisualText").checked = false;\n    $("visualTranslateHelp").textContent = same ? t("sameLanguageHelp") : t("visualTranslateHelp");\n  }\n',
)
replace(
    "frontend/app.js",
    '  $("resultMeta").textContent = utilityResult ? `${data.artifacts?.length || 0} ${t("tabFiles")}` : `${data.slides?.length || 0} ${t("tabSlides")} · ${data.quiz?.length || 0} Quiz · ${data.flashcards?.length || 0} ${t("tabCards")}`;\n  $("downloadAll").href = "#";\n  $("downloadAll").onclick = event => { event.preventDefault(); downloadProtected(`/jobs/${jobId}/download`, "LectureSift_Paketi.zip"); };\n',
    '  $("resultMeta").textContent = (utilityResult ? `${data.artifacts?.length || 0} ${t("tabFiles")}` : `${data.slides?.length || 0} ${t("tabSlides")} · ${data.quiz?.length || 0} Quiz · ${data.flashcards?.length || 0} ${t("tabCards")}`) + (data.download_locked ? ` · ${t("previewOnly")}` : "");\n  $("downloadLockPanel").hidden = !data.download_locked;\n  $("downloadAll").hidden = Boolean(data.download_locked);\n  $("downloadAll").setAttribute("aria-disabled", data.download_locked ? "true" : "false");\n  $("downloadAll").href = "#";\n  $("downloadAll").onclick = event => { event.preventDefault(); if (data.download_locked) { $("downloadLockPanel").scrollIntoView({behavior:"smooth"}); return; } downloadProtected(`/jobs/${jobId}/download`, "LectureSift_Paketi.zip"); };\n',
)
replace("frontend/app.js", 'data-protected-src="/jobs/${jobId}/slide/${encodeURIComponent(slide.file)}"', 'data-protected-src="/jobs/${jobId}/slide/${encodeURIComponent(slide.translated_file || slide.file)}"')
replace("frontend/app.js", '  renderQuiz(data.quiz || []); renderCards(); renderFiles(data.artifacts || []);\n', '  renderQuiz(data.quiz || []); renderCards(); renderFiles(data.artifacts || [], Boolean(data.download_locked));\n')
replace(
    "frontend/app.js",
    '  document.querySelectorAll(".quiz-option").forEach(button => button.onclick = () => {\n',
    '  if (items.some(item => item.answer_locked)) {\n    document.querySelectorAll(".quiz-explanation").forEach(node => node.hidden = true);\n    document.querySelectorAll(".quiz-option").forEach(button => { button.disabled = true; });\n    return;\n  }\n  document.querySelectorAll(".quiz-option").forEach(button => button.onclick = () => {\n',
)
replace(
    "frontend/app.js",
    'function renderFiles(files) {\n  $("filesContent").innerHTML = files.map(file =>',
    'function renderFiles(files, locked = false) {\n  if (locked) { $("filesContent").innerHTML = `<div class="empty-state"><p>${escapeHtml(t("downloadLockedText"))}</p><a class="unlock-link" href="/plans.html?plan=mini">${escapeHtml(t("unlockDownload"))}</a></div>`; return; }\n  $("filesContent").innerHTML = files.map(file =>',
)

# Main-page rollout should route purchasing to the dedicated checkout instead of creating a parallel payment flow.
replace("frontend/rollout.js", 'const names = {free:"Ücretsiz",credit:"Dakika Paketi",lite:"Lite",plus:"Plus",pro:"Pro",max:"Max",business:"Business",guest:"Misafir"};', 'const names = {free:"Ücretsiz",mini:"Mini",credit:"Dakika Paketi",lite:"Lite",plus:"Plus",pro:"Pro",max:"Max",business:"Business",guest:"Misafir"};')
start = '  async function createLocalizedTransferOrder(planCode, interval) {\n'
end = '\n  function workspacePlanCard(plan, currency, currentCode) {'
path = ROOT / "frontend/rollout.js"
text = path.read_text(encoding="utf-8")
left = text.find(start)
right = text.find(end, left)
if left < 0 or right < 0:
    raise RuntimeError("rollout.js purchase function markers not found")
replacement = '  async function createLocalizedTransferOrder(planCode, interval) {\n    const token = activeToken();\n    const guest = typeof billingAccount !== "undefined" && billingAccount?.plan?.code === "guest";\n    if (!token || guest) {\n      document.getElementById("accountPanel")?.scrollIntoView({behavior:"smooth"});\n      showInlineMessage("Plan satın almak için doğrulanmış hesabınla giriş yap.", true);\n      return;\n    }\n    location.href = `/plans.html?plan=${encodeURIComponent(planCode)}&interval=${encodeURIComponent(interval)}`;\n  }\n'
path.write_text(text[:left] + replacement + text[right:], encoding="utf-8")
replace("frontend/rollout.js", '<li>${esc((entitlements.export_formats || plan.export_formats || []).join(", ").toUpperCase())}</li>', '<li>${entitlements.download_enabled === false ? "Sınırlı önizleme · indirme yok" : esc((entitlements.export_formats || plan.export_formats || []).join(", ").toUpperCase())}</li>')
replace("frontend/rollout.js", 'note.textContent = "Hesapsız kullanım: bu cihazda tek seferlik, en fazla 5 dakikalık kaynak. Daha uzun işlemler için ücretsiz hesap oluştur.";', 'note.textContent = "Hesapsız kullanım: bu cihazda tek seferlik, en fazla 5 dakikalık sınırlı önizleme. Dosya indirme için Mini paket veya ücretli plan gerekir.";')

print("Frontend integration patch applied.")
